### ISSUE TITLE
QUIC connection errors. It works for an hour then breaks.

### ISSUE THREAD

**Issue by zs311521** [TechnitiumSoftware/DnsServer#1030]
Hi,

Please see sanitised logs below. I use local technitium forwarding to cloud hosted technitium. 

The funny thing is QUIC forwarding works for about an hour and then it suddenly stops. When it stops I can still ping with the dns client, but. Get a swathe of the below errors. It's definitely QUIC related because then I change to DOT and it works without any error permanently. 

2024-09-15 00:31:56 UTC] DNS Server failed to resolve the request 'placeholderwebsite.com. A IN' using forwarders: local.technitium:853 (cloud.technitium).
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request 'placeholderwebsite.com. A IN': request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.QuicClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\QuicClientConnection.cs:line 375
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4412
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4590
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4327
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4689
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4740
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass91_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4840
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4159
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4822
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3198
[2024-09-15 00:31:56 UTC] DNS Server failed to resolve the request 'anotherwebsite.com. A IN' using forwarders: local.technitium:853 (cloud.technitium).
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request 'anotherwebsite.com. A IN': request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.QuicClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\QuicClientConnection.cs:line 375
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4412
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4590
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass87_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4327
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4689
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4740

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The error log says that it failed to get a response from the server since the "request timed out". So, for some reasons, there is no response coming from the DoQ server. I am not really sure about the reason since it can be due to anything. QUIC is a very new protocol and the libraries that support QUIC are still a bit unstable and can have issues. 

It can also be an issue with your local network routers which has limited space in NAT table for UDP. Since QUIC uses UDP protocol, it may have issues with such routers with limited NAT table or which have buggy NAT implementation for UDP.

The issue can be better understood if you can run tcpdump on the DNS server when this issue starts to occur and capture packets for a couple of minutes while trying to resolve some domain name. Do share the pcap file that you capture with tcpdump if you need help with analyzing it. You can post the file here or send it to support@technitium.com.

**Comment by zs311521** [comment]
Thank you. I may have fixed it by increasing QUIC max inbound streams to 950 and listen backlog to 950. 

I have a lot of little devices performing queries so potentially it may have hit a limit and stopped working?

That or it'll break any moment now. But looks promising so far.

**Comment by ShreyasZare** [comment]
> Thank you @ShreyasZare may have fixed it by increasing QUIC max inbound streams to 950 and listen backlog to 950.

Both these option are for the DNS-over-QUIC server part and has no effect when you are using it just as a forwarder.

**Comment by zs311521** [comment]
> > Thank you @ShreyasZare may have fixed it by increasing QUIC max inbound streams to 950 and listen backlog to 950.
> 
> 
> 
> Both these option are for the DNS-over-QUIC server part and has no effect when you are using it just as a forwarder.

You're right. But what I did is I enabled IPv6 on my resolver server, so dns leak tests are finding both the ipv4 dns and IPv6. My understanding is that IPv6 does not have the issue of NAT. So far so good with IPv6 and quic!

**Comment by ShreyasZare** [comment]
> You're right. But what I did is I enabled IPv6 on my resolver server, so dns leak tests are finding both the ipv4 dns and IPv6. My understanding is that IPv6 does not have the issue of NAT. So far so good with IPv6 and quic!

Yes, that should help if you can use both the IPv4 and IPv6 networks so that if one fails to connect, you got another way to do the request.

**Comment by zs311521** [comment]
> > You're right. But what I did is I enabled IPv6 on my resolver server, so dns leak tests are finding both the ipv4 dns and IPv6. My understanding is that IPv6 does not have the issue of NAT. So far so good with IPv6 and quic!
> 
> 
> 
> Yes, that should help if you can use both the IPv4 and IPv6 networks so that if one fails to connect, you got another way to do the request.

Spoke too soon. Sadly Quic connections still stop working after an hour or two. I have to manually swap over to TLS which works like a treat. I can then turn on QUIC again but it breaks in an hour or two, and doesn't start up again until swapped over to DOT and then back to QUIC again after a period of time.

**Comment by ShreyasZare** [comment]
> Spoke too soon. Sadly Quic connections still stop working after an hour or two. I have to manually swap over to TLS which works like a treat. I can then turn on QUIC again but it breaks in an hour or two, and doesn't start up again until swapped over to DOT and then back to QUIC again after a period of time.

Cannot be sure what could be the issue here since QUIC can have strange issues due to network equipment with buggy UDP/NAT implementations.

**Comment by ShreyasZare** [comment]
@Chrislja thanks for the comment. I believe @zs311521 is running a personal home setup and for a small setup, the default values should be sufficient. But, this solution can be tried to see if it helps in anyway.

**Comment by ShreyasZare** [comment]
I guess I have found the bug causing this issue. Will test for a while to confirm and will release an update for it soon. This will also fix the #1041 issue.

**Comment by Chrislja** [comment]
@ShreyasZare perfect! Thank you. I’ve been having this problem for a while. Look forward to testing the fix when it’s available.

**Comment by ShreyasZare** [comment]
Its been almost 24 hrs of running DoQ test here and its working find with no issues. So looks like the fix is working well and there is no other issue. Will push an update soon with the fix.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.2 is now available which fixes this issue. Do update and let me know your feedback.
