### ISSUE TITLE
Issue with UDP Proxy

### ISSUE THREAD

**Issue by erroltuparker** [TechnitiumSoftware/DnsServer#1107]
I don't know when but there seems to have been some issue that happened when attempting to use the UDP Proxy option to reverse proxy the servers.

I note here that PROXY PROTOCOL should be working for UDP and works well for both TCP and HTTP.
https://github.com/TechnitiumSoftware/DnsServer/issues/590

I'm quite confident that I had this setup and working when it first came out but I changed tools and then eventually came back because nothing else worked quite as well and had the features I wanted like Technitium. Since coming back, no matter what reverse proxy i use, traefik or caddy, or what protocol version, it is never able to respond to a request via the the UDP PROXY port configuration.

If im using proxy_protocol v2, i get that its missing the PROXY HEADER error

If I use v1, i get that it is unable to parse the address.

Currently, i'm able to proxy it to the native UDP port (53), but then I lose the ability to track where the requests are coming.

Any insights?

**Comment by ShreyasZare** [comment]
Thanks for the post. Please share your reverse proxy config and screenshot of the DNS server Optional Protocols settings page so that I can understand your setup better.

**Comment by ShreyasZare** [comment]
Please share the DNS server's Optional Protocols config screenshot too. Also, do you see any errors logged in the DNS logs? If yes then please share the error logs too.

**Comment by erroltuparker** [comment]
This is when using proxy protocol v2

```
[2024-11-14 21:01:08 Local] [192.168.200.1:55995] [UDPPROXY] System.ArgumentNullException: Value cannot be null. (Parameter 'address')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Net.IPEndPoint..ctor(IPAddress address, Int32 port)
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 410
[2024-11-14 21:01:08 Local] [192.168.200.1:55995] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:01:18 Local] [192.168.200.1:55995] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
```

This is using v1
```
[2024-11-14 21:02:19 Local] [192.168.200.1:55188] [UDPPROXY] System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.ParseVersion1(String value) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 245
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 149
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:02:19 Local] [192.168.200.1:55188] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:02:19 Local] [192.168.200.1:39127] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:02:19 Local] [192.168.200.1:46580] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:02:20 Local] [192.168.200.1:49345] [UDPPROXY] System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.ParseVersion1(String value) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 245
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 149
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
[2024-11-14 21:02:20 Local] [192.168.200.1:49345] [UDPPROXY] System.IO.InvalidDataException: The stream does not contain PROXY protocol header.
   at TechnitiumLibrary.Net.ProxyProtocol.ProxyProtocolStream.CreateAsServerAsync(Stream baseStream, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\ProxyProtocol\ProxyProtocolStream.cs:line 138
   at DnsServerCore.Dns.DnsServer.ReadUdpRequestAsync(Socket udpListener, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 409
```

**Comment by ShreyasZare** [comment]
Thanks for the details. I tested it in my setup with nginx as the reverse proxy and its working without any issues for both TCP and UDP proxy cases.

I would suggest that you run `tcpdump -i any -w test.pcap` command on the server that is running DNS and test it again. Share the test.pcap file over here or email it to support@technitium.com. This will allow debugging the issue better as it will be clear what data is being actually received by the DNS server.

**Comment by erroltuparker** [comment]
Hi @ShreyasZare and @skedastically 

Thanks for testing and confirming my issue with caddy, i've raised a issue on their side https://github.com/mholt/caddy-l4/issues/269

I did also confirm that the work around did work as well, I just wish I could do a double proxy caddy -> nginx -> dns but as you have mentioned, the UDP proxying doesn't quite work properly and it seems that nginx only receives listen 53 proxy_protocol on tcp (could be wrong).

@skedastically yeah that was a work around I was using in the meanwhile to get it to respond, though because its not hitting the proxy port, it doesn't log it correctly and forgot to provide what the config should have been.
