### ISSUE TITLE
Failover App no longer working

### ISSUE THREAD

**Issue by jk111** [TechnitiumSoftware/DnsServer#1112]
I have a TCP check called tcp3890 to check the status of my LDAP service. This is being used to update my "ldap" record for my domain. Been working great up until recently. Here are the logs when the service fails over. The DNS record is not being updated. Running 13.1.1 and failover app version 8.

**App Config:**
`    {
      "name": "tcp3890",
      "type": "tcp",
      "interval": 15,
      "retries": 2,
      "timeout": 5,
      "port": 3890,
      "emailAlert": "default",
      "webHook": "default"
    },`

**DNS Record**
`{
  "primary": [
    "192.168.1.5"
  ],
  "secondary": [
    "192.168.1.10"
  ],
  "serverDown": [
    "172.16.10.10"
  ],
  "healthCheck": "tcp3890",
  "allowTxtStatus": false,
  "healthCheckUrl": "null"
}`

**Log messages during failover:**
`[2024-11-15 15:55:36 UTC] DNS App [Failover]: ALERT! Address [192.168.1.5] status is FAILED based on 'tcp3890' health check. The failure reason is: Connection timed out.
[2024-11-15 15:55:36 UTC] DNS App [Failover]: System.TimeoutException: The operation has timed out.
   at TechnitiumLibrary.TaskExtensions.TimeoutAsync(Func`2 func, Int32 timeout, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary\TaskExtensions.cs:line 38
   at TechnitiumLibrary.TaskExtensions.TimeoutAsync(Func`2 func, Int32 timeout, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary\TaskExtensions.cs:line 43
   at Failover.HealthCheck.IsHealthyAsync(IPAddress address, Uri healthCheckUrl) in Z:\Technitium\Projects\DnsServer\Apps\FailoverApp\HealthCheck.cs:line 346`

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Do you mean to say that the DNS server returns the primary IP when queried for the domain? Since the APP record itself is never modified, the response is dynamically generated.

I would suggest that you set `allowTxtStatus` to `true` and query the domain for TXT record to get the health status in response. Share any output from the test you do.
