### ISSUE TITLE
Received a response without AuthoritativeAnswer flag set from Name server

### ISSUE THREAD

**Issue by thargy** [TechnitiumSoftware/DnsServer#1146]
I set up a clean install of technitium on Proxmox using [this script](https://tteck.github.io/Proxmox/#technitium-dns-lxc).

After logging in I tried to use DNS Client to resolve 'google.com', but got the following:
```json
{
  "Metadata": {
    "NameServer": "technitiumdns.lan (192.168.86.3)",
    "Protocol": "Udp",
    "DatagramSize": "63 bytes",
    "RoundTripTime": "4.34 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "ServerFailure",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "20 bytes",
        "Data": {
          "InfoCode": "Other",
          "ExtraText": "Resolver exception"
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [
    {
      "InfoCode": "NoReachableAuthority",
      "ExtraText": "technitiumdns.lan (192.168.86.3) returned RCODE=ServerFailure for google.com. A IN"
    }
  ],
  "Identifier": 23449,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "ServerFailure",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "google.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "1232",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "24 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "20 bytes",
            "Data": {
              "InfoCode": "Other",
              "ExtraText": "Resolver exception"
            }
          }
        ]
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

Using `Recursive Query {recursive-resolver}` works, as does `System DNS {system-dns}`:
```json
{
  "Metadata": {
    "NameServer": "i.root-servers.net (192.36.148.17)",
    "Protocol": "Udp",
    "DatagramSize": "55 bytes",
    "RoundTripTime": "39.72 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 512,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "Identifier": 0,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": false,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "google.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "google.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "268 (4 mins 28 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "142.250.187.238"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "512",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

The logs show:

```
[2024-12-06 17:10:08 UTC] DNS Server failed to resolve the request '3.86.168.192.in-addr.arpa. PTR IN'.
TechnitiumLibrary.Net.Dns.DnsClientFailureResponseException: DnsClient failed to resolve the request '. NS IN'. Received a response without AuthoritativeAnswer flag set from Name server: a.root-servers.net (198.41.0.4)
   at TechnitiumLibrary.Net.Dns.DnsClient.GetRootServersUsingRootHintsAsync(IDnsCache cache, NetProxy proxy, Boolean preferIPv6, UInt16 udpPayloadSize, Boolean dnssecValidation, Int32 retries, Int32 timeout, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2698
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, UInt16 udpPayloadSize, Boolean randomizeName, Boolean qnameMinimization, Boolean dnssecValidation, NetworkAddress eDnsClientSubnet, Int32 retries, Int32 timeout, Int32 concurrency, Int32 maxStackCount, Boolean minimalResponse, Boolean asyncNsRevalidation, Boolean asyncNsResolution, List`1 rawResponses, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 971
   at TechnitiumLibrary.TaskExtensions.TimeoutAsync[T](Func`2 func, Int32 timeout, CancellationToken cancellationToken)
   at TechnitiumLibrary.TaskExtensions.TimeoutAsync[T](Func`2 func, Int32 timeout, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary\TaskExtensions.cs:line 65
   at DnsServerCore.Dns.DnsServer.DefaultRecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, IDnsCache dnsCache, Boolean dnssecValidation, Boolean skipDnsAppAuthoritativeRequestHandlers, CancellationToken cancellationToken) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3398
   at DnsServerCore.Dns.DnsServer.RecursiveResolverBackgroundTaskAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3158
```

Next, I tried to explicitly set the IPv4 and IPv6 addresses in Settings->General, but I get the same failure.

**Comment by ShreyasZare** [comment]
Thanks for the post. This issue has nothing to do with the DNS server or any of the settings. Its just that your ISP is hijacking all outbound DNS requests so all your DNS requests to any server is actually being answered by your ISP's DNS server. Which is why you are seeing that a root server is giving you an answer for "google.com". 

This means that you wont be able to run a recursive resolver with your current ISP. I would recommend that you configure a forwarder in Settings > Proxy & Forwarders section which uses encrypted DNS protocol. This will ensure that your ISP wont be able to hijack/tamper your DNS requests.

**Comment by thargy** [comment]
Thanks for answering so quickly. I was very confused, though, as the `Recursive Resolver` test works fine.

More importantly, I'm trying Technitium, as it was recommended on several forums for my use case over AdGuard and piHole. Specifically, I am using a Dream Machine Pro as my primary router and DHCP connected to the internet via BT Fibre Broadband (which is by far the most common connection in the UK).

I want to use something other than Technitium as the DHCP server or primary DNS server. Instead, I want to continue reserving IPs and managing DNS settings on the DMP. I'm also not using Technitium to provide DNS outside of my LAN. I'm only using it (for now) as an ad/malware block. This would be a reasonably common use case.

I made the mistake of thinking that putting the IP of my DMP/router in `Settings->General->DNS Server IPv4 Source Addresses` would have the desired effect. However, adding it to `Settings->Proxy & Forwarders->Forwarders` seems to have worked. Sadly, the tutorials I was following never mentioned this.

**Comment by thargy** [comment]
Closing.
