### ISSUE TITLE
Remote syslog server support

### ISSUE THREAD

**Issue by rlagmlah** [TechnitiumSoftware/DnsServer#133]
Hi.
TechnitiumDNS seems to have a lot of logs. If query logging is used, the log file is larger.
I am currently trying to centralize logs using the graylog server.
If TechnitiumDNS supports a remote syslog server, I think all logs can be gathered in one place for more efficient management.
thank.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Syslog support is in my to do list already.

**Comment by EHRETic** [comment]
If I can upvote that Feature Request a little... I'm starting to use Wazuh and want some logs too! :-)

**Comment by ShreyasZare** [comment]
> @ShreyasZare, I didn't see any news from Technitium since a while so I hope you and your family are safe and in good shape... 😉 But if you are, what are the upcoming news?
> 
> My DNS servers are running fine and I have nothing to complain but I'm always curious to know what is coming next!
> 
> Let us know Kind regards

Thanks for asking. All is well here as usual. Its just that the next update is taking more time due to DNSSEC implementation which is quite complex. 

Good news is that the implementation is almost done with a couple of things remaining to implement and the overall integration testing.

I was expecting it to be completed by this month but its taking slightly more time so should be ready for release by next month.

**Comment by EHRETic** [comment]
> Thanks for asking. All is well here as usual. Its just that the next update is taking more time due to DNSSEC implementation which is quite complex.

That is very cool, thanks a lot! 😊

**Comment by jthoel** [comment]
I see 9.1 was released and while looking around, I still don't see any options for sending logs to a syslog server for correlation or auditing.  Is this still a feature request?

**Comment by ShreyasZare** [comment]
> I see 9.1 was released and while looking around, I still don't see any options for sending logs to a syslog server for correlation or auditing. Is this still a feature request?

Yes, the feature is planned but still not implemented due to demand for other features that were prioritized. I will update here when the feature is available.

**Comment by PhilRumi** [comment]
This would be highly beneficial. are there any estimates on potential timeline for this one?

**Comment by ShreyasZare** [comment]
> This would be highly beneficial. are there any estimates on potential timeline for this one?

Syslog support and DHCPv6 are planned to be implemented after the current major version release that will be available in a couple of weeks. So it may take about a couple of months by current estimate.

**Comment by ytimenkov** [comment]
Came across this issue... Just adding an option to write to console instead of files would solve a lot of cases...
It's quite natural way for logging in containers and I'm trying to run it from flash memory and would like to avoid unnecessary writes, so it's either journald's in-memory buffer or remote logging.

But glad to hear that you have plans for it!

**Comment by ShreyasZare** [comment]
> Came across this issue... Just adding an option to write to console instead of files would solve a lot of cases... It's quite natural way for logging in containers and I'm trying to run it from flash memory and would like to avoid unnecessary writes, so it's either journald's in-memory buffer or remote logging.
> 
> But glad to hear that you have plans for it!

Thanks for the suggestion. Will add option for logging to console.

**Comment by ShreyasZare** [comment]
@vanhecke Thanks for the feedback. There is no explicit code that checks for the header syntax and it just assigns it to the HTTP client. Do you see any errors in the DNS logs related to this? Share any error log that you see here.

**Comment by vanhecke** [comment]
@ShreyasZare 

![Image](https://github.com/user-attachments/assets/31bd6983-a8e8-478a-85d1-34f65d2f3804)

**Comment by ShreyasZare** [comment]
@vanhecke thanks for the details. Please check the DNS logs from the admin panel and find the full error log that you see for this error in screenshot. Share the error log here.

**Comment by ShreyasZare** [comment]
> ```
> [2025-03-04 11:12:38 UTC] [10.13.37.153:52311] System.FormatException: The format of value 'Mzk6akJo<SNIP>Y2UnZmNWdramw=' is invalid.
>    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
>    at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
>    at LogExporter.Strategy.HttpExportStrategy.CustomHttpClient.Configure(IConfiguration configuration) in Z:\Technitium\Projects\DnsServer\Apps\LogExporterApp\Strategy\HttpExportStrategy.cs:line 96
>    at Serilog.LoggerSinkConfigurationExtensions.Http(LoggerSinkConfiguration sinkConfiguration, String requestUri, Nullable`1 queueLimitBytes, Nullable`1 logEventLimitBytes, Nullable`1 logEventsInBatchLimit, Nullable`1 batchSizeLimitBytes, Nullable`1 period, Boolean flushOnClose, ITextFormatter textFormatter, IBatchFormatter batchFormatter, LogEventLevel restrictedToMinimumLevel, LoggingLevelSwitch levelSwitch, IHttpClient httpClient, IConfiguration configuration)
>    at LogExporter.Strategy.HttpExportStrategy..ctor(String endpoint, Dictionary`2 headers) in Z:\Technitium\Projects\DnsServer\Apps\LogExporterApp\Strategy\HttpExportStrategy.cs:line 54
>    at LogExporter.App.InitializeAsync(IDnsServer dnsServer, String config) in Z:\Technitium\Projects\DnsServer\Apps\LogExporterApp\App.cs:line 112
>    at DnsServerCore.Dns.Applications.DnsApplication.SetConfigAsync(String config) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Applications\DnsApplication.cs:line 230
>    at DnsServerCore.DnsWebService.WebServiceAppsApi.SetAppConfigAsync(HttpContext context) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceAppsApi.cs:line 695
>    at DnsServerCore.DnsWebService.WebServiceApiMiddleware(HttpContext context, RequestDelegate next) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 681
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
> ```
> 
> PS. Syslog over UDP is working but HTTP would be cleaner for my setup.

Thanks for the error log. The error is coming from the HTTP Client code which is expecting that the header used has value as per standards. Will update the app to allow it to accept raw header value without any validation.

**Comment by ShreyasZare** [comment]
@vanhecke Technitium DNS Server v13.5 is now available that fixes the issue you reported. Do update and let me know your feedback.

**Comment by ShreyasZare** [comment]
Thanks for asking. Syslog support for all log entries will take some time.Meanwhile, I guess there may be some solution that exports stdout data to syslog. You can enable logging to console from Settings.

**Comment by ShreyasZare** [comment]
I have not tried any specific solution but there are a few that you can find by searching for "stdout to syslog".
