### ISSUE TITLE
5.0.1 resolver stalls

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#153]
In 5.0.1 the DNS resolver stalls after it receives bad queries with a colon. It'll load results from the cache but new records will fail.

Here's a partial log file that demonstrates what happens right before it stalls:

[2020-07-13 07:04:15 UTC] [192.168.50.1:30975] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)

[2020-07-13 07:04:16 UTC] [192.168.50.1:40388] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080.localdomain]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)

[2020-07-13 07:39:15 UTC] [192.168.50.1:28897] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)
[2020-07-13 07:39:15 UTC] [192.168.50.1:21549] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080.localdomain]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)

[2020-07-13 08:09:15 UTC] [192.168.50.1:30933] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)
[2020-07-13 08:09:15 UTC] [192.168.50.1:24578] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080.localdomain]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)

[2020-07-13 08:44:15 UTC] [192.168.50.1:26826] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)
[2020-07-13 08:44:15 UTC] [192.168.50.1:43565] [UDP] TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [192.168.0.12:9080.localdomain]: invalid character [58] was found.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertToByteKey(String domain)
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains)
   at DnsServerCore.Dns.ZoneManagers.AuthZoneManager.Query(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol)
(Repeats X 4)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The error logs are as expected. For any query with an invalid character will throw this error and it will get logged. This is a built in validation into the new tree data structure that stores zone data.

**Comment by ShreyasZare** [comment]
New version is now available. Please check if the issue is fixed and reopen this issue if needed.
