### ISSUE TITLE
DNS resolution issues - connection timed out

### ISSUE THREAD

**Issue by lfarrand** [TechnitiumSoftware/DnsServer#203]
Hi,

I'm having some trouble with DNS resolution in the latest build. I suspect it might be related to how I have my network configured. I have 9 VLANs and an untagged / trunk network. Technitium is acting as the DHCP & DNS server for each network, and is listening for DNS queries on the default 0.0.0.0:53.

If I run the dig command and try to resolve a domain name from another machine, I more often than not get a 'connection timed out; no servers could be reached' if using UDP, or 'connection refused' if using TCP. Every now and again (maybe 1% of the time), the queries work fine, so it is a little puzzling to say the least.

If I run the same dig command on the DNS server host iself, the queries work fine as expected.

Here is the log file from the period during which I ran the queries:

    [2020-12-05 06:26:42 UTC] DNS Server config file was loaded: /etc/dns/config/dns.config
    [2020-12-05 06:26:42 UTC] DNS Server successfully loaded zone file: /etc/dns/config/zones/lan.zone
    [2020-12-05 06:26:42 UTC] DNS Server successfully loaded zone file: /etc/dns/config/zones/123.168.192.in-addr.arpa.zone
    [2020-12-05 06:26:42 UTC] DNS Server successfully loaded zone file: /etc/dns/config/zones/10.168.192.in-addr.arpa.zone
    [2020-12-05 06:26:42 UTC] DNS Server successfully loaded zone file: /etc/dns/config/zones/100.168.192.in-addr.arpa.zone
    [2020-12-05 06:26:42 UTC] DNS Server is loading allowed zone file: /etc/dns/config/allowed.config
    [2020-12-05 06:26:42 UTC] DNS Server is loading blocked zone file: /etc/dns/config/blocked.config
    [2020-12-05 06:26:42 UTC] DNS Server is reading block list from: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
    [2020-12-05 06:26:42 UTC] [0.0.0.0:53] [UDP] DNS Server was bound successfully.
    [2020-12-05 06:26:42 UTC] [0.0.0.0:53] [TCP] DNS Server was bound successfully.
    [2020-12-05 06:26:42 UTC] [0.0.0.0:80] [HTTP] DNS Server was bound successfully.
    [2020-12-05 06:26:42 UTC] DNS Server block list file was read (60424 domains) from: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
    [2020-12-05 06:26:42 UTC] DNS Server is reading block list from: https://mirror1.malwaredomains.com/files/justdomains
    [2020-12-05 06:26:42 UTC] [0.0.0.0:67] DHCP Server successfully activated scope: Default LAN (192.168.123.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: Default LAN (192.168.123.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/Default LAN (192.168.123.x).scope
    [2020-12-05 06:26:42 UTC] DNS Server block list file was read (26854 domains) from: https://mirror1.malwaredomains.com/files/justdomains
    [2020-12-05 06:26:42 UTC] DNS Server is reading block list from: https://dbl.oisd.nl/
    [2020-12-05 06:26:42 UTC] [0.0.0.0:67] DHCP Server successfully activated scope: VLAN10 - Servers (192.168.10.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN10 - Servers (192.168.10.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN10 - Servers (192.168.10.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.50.2:67] DHCP Server successfully activated scope: VLAN50 - Smart Home WiFi (192.168.50.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN50 - Smart Home WiFi (192.168.50.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN50 - Smart Home WiFi (192.168.50.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.30.2:67] DHCP Server successfully activated scope: VLAN30 - Home WiFi (192.168.30.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN30 - Home WiFi (192.168.30.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN30 - Home WiFi (192.168.30.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.20.2:67] DHCP Server successfully activated scope: VLAN20 - Desktops (192.168.20.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN20 - Desktops (192.168.20.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN20 - Desktops (192.168.20.x).scope
    [2020-12-05 06:26:42 UTC] [0.0.0.0:67] DHCP Server successfully activated scope: VLAN11 - NAS (192.168.11.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN11 - NAS (192.168.11.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN11 - NAS (192.168.11.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.100.2:67] DHCP Server successfully activated scope: VLAN100 - Raspberry Pi (192.168.100.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN100 - Raspberry Pi (192.168.100.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN100 - Raspberry Pi (192.168.100.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.12.2:67] DHCP Server successfully activated scope: VLAN12 - Docker (192.168.12.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN12 - Docker (192.168.12.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN12 - Docker (192.168.12.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.40.2:67] DHCP Server successfully activated scope: VLAN40 - Guest WiFi (192.168.40.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN40 - Guest WiFi (192.168.40.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN40 - Guest WiFi (192.168.40.x).scope
    [2020-12-05 06:26:42 UTC] [192.168.60.2:67] DHCP Server successfully activated scope: VLAN60 - Media (192.168.60.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope: VLAN60 - Media (192.168.60.x)
    [2020-12-05 06:26:42 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN60 - Media (192.168.60.x).scope
    [2020-12-05 06:26:42 UTC] [0.0.0.0:5380] Web Service (v5.5.0.0) was started successfully.
    [2020-12-05 06:26:43 UTC] DNS Server block list file was read (1172520 domains) from: https://dbl.oisd.nl/
    [2020-12-05 06:26:43 UTC] DNS Server is reading block list from: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    [2020-12-05 06:26:43 UTC] DNS Server block list file was read (2701 domains) from: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    [2020-12-05 06:26:43 UTC] DNS Server is reading block list from: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    [2020-12-05 06:26:43 UTC] DNS Server block list file was read (34 domains) from: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    [2020-12-05 06:26:43 UTC] DNS Server is reading block list from: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    [2020-12-05 06:26:43 UTC] DNS Server block list file was read (58229 domains) from: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    [2020-12-05 06:26:44 UTC] DNS Server block list zone was loaded successfully.

Here is the CLI output from the above queries.

From the other machine:

    <user>@<machine>:~$ dig +trace @192.168.123.2 bbc.com
    
    ; <<>> DiG 9.16.1-Ubuntu <<>> +trace @192.168.123.2 bbc.com
    ; (1 server found)
    ;; global options: +cmd
    ;; connection timed out; no servers could be reached
    
    <user>@<machine>:~$ dig +tcp +trace @192.168.123.2 bbc.com
    ;; Connection to 192.168.123.2#53(192.168.123.2) for bbc.com failed: connection refused.

From the DNS server host iself:

    <user>@<dns server>:~# dig +trace @192.168.123.2 bbc.com
    
    ; <<>> DiG 9.16.1-Ubuntu <<>> +trace @192.168.123.2 bbc.com
    ; (1 server found)
    ;; global options: +cmd
    .                       509868  IN      NS      a.root-servers.net.
    .                       509868  IN      NS      b.root-servers.net.
    .                       509868  IN      NS      c.root-servers.net.
    .                       509868  IN      NS      d.root-servers.net.
    .                       509868  IN      NS      e.root-servers.net.
    .                       509868  IN      NS      f.root-servers.net.
    .                       509868  IN      NS      g.root-servers.net.
    .                       509868  IN      NS      h.root-servers.net.
    .                       509868  IN      NS      i.root-servers.net.
    .                       509868  IN      NS      j.root-servers.net.
    .                       509868  IN      NS      k.root-servers.net.
    .                       509868  IN      NS      l.root-servers.net.
    .                       509868  IN      NS      m.root-servers.net.
    ;; Received 800 bytes from 192.168.123.2#53(192.168.123.2) in 4 ms
    
    ;; Connection to 2001:500:9f::42#53(2001:500:9f::42) for bbc.com failed: network unreachable.
    ;; Connection to 2001:500:12::d0d#53(2001:500:12::d0d) for bbc.com failed: network unreachable.
    ;; Connection to 2001:dc3::35#53(2001:dc3::35) for bbc.com failed: network unreachable.
    com.                    172800  IN      NS      a.gtld-servers.net.
    com.                    172800  IN      NS      b.gtld-servers.net.
    com.                    172800  IN      NS      c.gtld-servers.net.
    com.                    172800  IN      NS      d.gtld-servers.net.
    com.                    172800  IN      NS      e.gtld-servers.net.
    com.                    172800  IN      NS      f.gtld-servers.net.
    com.                    172800  IN      NS      g.gtld-servers.net.
    com.                    172800  IN      NS      h.gtld-servers.net.
    com.                    172800  IN      NS      i.gtld-servers.net.
    com.                    172800  IN      NS      j.gtld-servers.net.
    com.                    172800  IN      NS      k.gtld-servers.net.
    com.                    172800  IN      NS      l.gtld-servers.net.
    com.                    172800  IN      NS      m.gtld-servers.net.
    com.                    86400   IN      DS      30909 8 2 E2D3C916F6DEEAC73294E8268FB5885044A833FC5459588F4A9184CF C41A5766
    com.                    86400   IN      RRSIG   DS 8 1 86400 20201218050000 20201205040000 26116 . mLP5l5LolcOMwcBnESt7L77gRBwnB3ojGzfYEXkqwfBWAYELjk7Wrvxh xvGvStNAcbCKuYqSVNw0mFpdy1qVCq2Ig9bDrbihSbumstB/C1B8snut FPdJKs+NZVFve2wwMFd7rwaPUFDvB0aAxXO/    D05ih3NiKkCJVca3Pqh6 Z9KThZyZeV/SSikSFL5LxrCkDDWOe9w+EN3G9wmNBXo2qf/stmizslAF W7mFIxeCzJDQ+pd01dWdgSNdhlj18QaUf9avSY8GABYIQNi6idd7N3xu gMYYH0cs8rPtlAXgm8pw2zVlud1LZaL1dJ8yj/L+8rKjSuwcNZSNSn5o 7O4nJQ==
    ;; Received 1167 bytes from 199.7.91.13#53(d.root-servers.net) in 84 ms
    
    ;; Connection to 2001:500:856e::30#53(2001:500:856e::30) for bbc.com failed: network unreachable.
    ;; Connection to 2001:502:1ca1::30#53(2001:502:1ca1::30) for bbc.com failed: network unreachable.
    bbc.com.                172800  IN      NS      ns0.bbcdns.net.uk.
    bbc.com.                172800  IN      NS      ns1.bbcdns.net.uk.
    bbc.com.                172800  IN      NS      ns0.bbcdns.net.
    bbc.com.                172800  IN      NS      ns1.bbcdns.net.
    CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A NS SOA RRSIG DNSKEY NSEC3PARAM
    CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN RRSIG NSEC3 8 2 86400 20201211054008 20201204043008 31510 com. nxRtOB7D290koawJkkzhQTtraL4b1VDsVKMpwydIPbOekNRhh02fFJH6 27niSbNdWxhaRYHCXVqS245HlytxVQa0m0mTSN3F99j+OKSqeudMbzc/     Xyohx1eoRu3uolNCDjnUg55/xIZf5RbDSAhvfZhwlV3RhR3Ru12DwPOc hH6K9aVKzYcE9itqj+xkYaougqrd4JFYbYlM0O9wm5x+6w==
    CQH5434VH4L6T3E81NRIFFIPMA2BL7I6.com. 86400 IN NSEC3 1 1 0 - CQH5LJASLNMU8G8QJES2UHM8KCHCE356 NS DS RRSIG
    CQH5434VH4L6T3E81NRIFFIPMA2BL7I6.com. 86400 IN RRSIG NSEC3 8 2 86400 20201210070724 20201203055724 31510 com. K+ipzGRZ5ixvsPXatdGSk9vsc53M1GyRmdp6BziMBv34Zt+RlIeMYbNz eHqpsev7xlNXRrd3geBtCibgvM1Dr+Fz9nL4FjctSwh5I4PxUhRtSHpK     BtLuC7dJCpyWbWopn10CHbunvs6Dh5esJcgjsIMXBkqS85yrYeqVUUDX PZXg+cxmiLjDEfO7sArivM694qaDj5jP0Xz0w43Fcek1MQ==
    ;; Received 680 bytes from 192.5.6.30#53(a.gtld-servers.net) in 24 ms
    
    ;; Connection to 2a00:edc0:6259:7:9::4#53(2a00:edc0:6259:7:9::4) for bbc.com failed: network unreachable.
    ;; Connection to 2620:4d:4000:6259:7:9:0:1#53(2620:4d:4000:6259:7:9:0:1) for bbc.com failed: network unreachable.
    ;; Connection to 2620:4d:4000:6259:7:9:0:3#53(2620:4d:4000:6259:7:9:0:3) for bbc.com failed: network unreachable.
    bbc.com.                300     IN      A       151.101.0.81
    bbc.com.                300     IN      A       151.101.64.81
    bbc.com.                300     IN      A       151.101.128.81
    bbc.com.                300     IN      A       151.101.192.81
    ;; Received 100 bytes from 198.51.45.9#53(ns1.bbcdns.net) in 8 ms
    
    <user>@<dns server>:~# dig +tcp +trace @192.168.123.2 bbc.com
    
    ; <<>> DiG 9.16.1-Ubuntu <<>> +tcp +trace @192.168.123.2 bbc.com
    ; (1 server found)
    ;; global options: +cmd
    .                       509861  IN      NS      a.root-servers.net.
    .                       509861  IN      NS      b.root-servers.net.
    .                       509861  IN      NS      c.root-servers.net.
    .                       509861  IN      NS      d.root-servers.net.
    .                       509861  IN      NS      e.root-servers.net.
    .                       509861  IN      NS      f.root-servers.net.
    .                       509861  IN      NS      g.root-servers.net.
    .                       509861  IN      NS      h.root-servers.net.
    .                       509861  IN      NS      i.root-servers.net.
    .                       509861  IN      NS      j.root-servers.net.
    .                       509861  IN      NS      k.root-servers.net.
    .                       509861  IN      NS      l.root-servers.net.
    .                       509861  IN      NS      m.root-servers.net.
    ;; Received 800 bytes from 192.168.123.2#53(192.168.123.2) in 0 ms
    
    com.                    172800  IN      NS      k.gtld-servers.net.
    com.                    172800  IN      NS      a.gtld-servers.net.
    com.                    172800  IN      NS      h.gtld-servers.net.
    com.                    172800  IN      NS      b.gtld-servers.net.
    com.                    172800  IN      NS      c.gtld-servers.net.
    com.                    172800  IN      NS      e.gtld-servers.net.
    com.                    172800  IN      NS      g.gtld-servers.net.
    com.                    172800  IN      NS      d.gtld-servers.net.
    com.                    172800  IN      NS      l.gtld-servers.net.
    com.                    172800  IN      NS      j.gtld-servers.net.
    com.                    172800  IN      NS      i.gtld-servers.net.
    com.                    172800  IN      NS      m.gtld-servers.net.
    com.                    172800  IN      NS      f.gtld-servers.net.
    com.                    86400   IN      DS      30909 8 2 E2D3C916F6DEEAC73294E8268FB5885044A833FC5459588F4A9184CF C41A5766
    com.                    86400   IN      RRSIG   DS 8 1 86400 20201218050000 20201205040000 26116 . mLP5l5LolcOMwcBnESt7L77gRBwnB3ojGzfYEXkqwfBWAYELjk7Wrvxh xvGvStNAcbCKuYqSVNw0mFpdy1qVCq2Ig9bDrbihSbumstB/C1B8snut FPdJKs+NZVFve2wwMFd7rwaPUFDvB0aAxXO/    D05ih3NiKkCJVca3Pqh6 Z9KThZyZeV/SSikSFL5LxrCkDDWOe9w+EN3G9wmNBXo2qf/stmizslAF W7mFIxeCzJDQ+pd01dWdgSNdhlj18QaUf9avSY8GABYIQNi6idd7N3xu gMYYH0cs8rPtlAXgm8pw2zVlud1LZaL1dJ8yj/L+8rKjSuwcNZSNSn5o 7O4nJQ==
    ;; Received 1195 bytes from 192.33.4.12#53(c.root-servers.net) in 16 ms
    
    ;; Connection to 2001:503:d414::30#53(2001:503:d414::30) for bbc.com failed: network unreachable.
    bbc.com.                172800  IN      NS      ns0.bbcdns.net.uk.
    bbc.com.                172800  IN      NS      ns1.bbcdns.net.uk.
    bbc.com.                172800  IN      NS      ns0.bbcdns.net.
    bbc.com.                172800  IN      NS      ns1.bbcdns.net.
    CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A NS SOA RRSIG DNSKEY NSEC3PARAM
    CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN RRSIG NSEC3 8 2 86400 20201211054008 20201204043008 31510 com. nxRtOB7D290koawJkkzhQTtraL4b1VDsVKMpwydIPbOekNRhh02fFJH6 27niSbNdWxhaRYHCXVqS245HlytxVQa0m0mTSN3F99j+OKSqeudMbzc/     Xyohx1eoRu3uolNCDjnUg55/xIZf5RbDSAhvfZhwlV3RhR3Ru12DwPOc hH6K9aVKzYcE9itqj+xkYaougqrd4JFYbYlM0O9wm5x+6w==
    CQH5434VH4L6T3E81NRIFFIPMA2BL7I6.com. 86400 IN NSEC3 1 1 0 - CQH5LJASLNMU8G8QJES2UHM8KCHCE356 NS DS RRSIG
    CQH5434VH4L6T3E81NRIFFIPMA2BL7I6.com. 86400 IN RRSIG NSEC3 8 2 86400 20201210070724 20201203055724 31510 com. K+ipzGRZ5ixvsPXatdGSk9vsc53M1GyRmdp6BziMBv34Zt+RlIeMYbNz eHqpsev7xlNXRrd3geBtCibgvM1Dr+Fz9nL4FjctSwh5I4PxUhRtSHpK     BtLuC7dJCpyWbWopn10CHbunvs6Dh5esJcgjsIMXBkqS85yrYeqVUUDX PZXg+cxmiLjDEfO7sArivM694qaDj5jP0Xz0w43Fcek1MQ==
    ;; Received 680 bytes from 192.52.178.30#53(k.gtld-servers.net) in 20 ms
    
    ;; Connection to 2620:4d:4000:6259:7:9:0:3#53(2620:4d:4000:6259:7:9:0:3) for bbc.com failed: network unreachable.
    bbc.com.                300     IN      A       151.101.0.81
    bbc.com.                300     IN      A       151.101.64.81
    bbc.com.                300     IN      A       151.101.128.81
    bbc.com.                300     IN      A       151.101.192.81
    ;; Received 100 bytes from 198.51.44.73#53(ns0.bbcdns.net.uk) in 8 ms

Any ideas about what might be causing this behaviour?

Thanks,

Lee

**Comment by lfarrand** [comment]
I've also noticed this error in the log, not sure if it's related or not.

    [2020-12-05 06:58:25 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN100 - Raspberry Pi (192.168.100.x).scope
    [2020-12-05 06:58:25 UTC] [192.168.123.57:38160] [UDP] System.NullReferenceException: Object reference not set to an instance of an object.
       at TechnitiumLibrary.ByteTree.ByteTree`2.GetOrAdd(TKey key, Func`2 valueFactory) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.ByteTree\ByteTree.cs:line 172
       at TechnitiumLibrary.ByteTree.ByteTree`2.GetOrAdd(TKey key, TValue value) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.ByteTree\ByteTree.cs:line 179
       at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaNameServers, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation) in     Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1503
       at DnsServerCore.Dns.DnsServer.ProcessRecursiveQueryAsync(DnsDatagram request, IReadOnlyList`1 viaNameServers, IReadOnlyList`1 viaForwarders, Boolean checkForCnameCloaking, Boolean cacheRefreshOperation) in     Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1385
       at DnsServerCore.Dns.DnsServer.ProcessQueryAsync(DnsDatagram request, IPEndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 930

**Comment by lfarrand** [comment]
Interestingly, it only appears to be a problem on my untagged network: Default LAN (192.168.123.x)

I can resolve DNS using any of the other interfaces without any problem.

**Comment by lfarrand** [comment]
I just tried to resolve DNS entries on a few interfaces, and found that while 192.168.10.2 and 192.168.12.2 worked fine, 192.168.11.2 didn't and failed with the following:

    $ dig +trace @192.168.11.2 bbc.com
    ;; reply from unexpected source: 192.168.10.2#53, expected 192.168.11.2#53

Is this expected? Shouldn't it be replying on the same interface?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Since you are getting "reply from unexpected source", this can be fixed by specifying a fixed end point as the DNS Server Local End Points in Settings and then use the one IP address for all your networks. I am assuming all your networks are routeable and can access the DNS. 

For networks that cannot reach the DNS server end point, add another Local Endpoint on the DNS server which is reachable from the network.

**Comment by ShreyasZare** [comment]
> 
> 
> I've also noticed this error in the log, not sure if it's related or not.
> 
> ```
> [2020-12-05 06:58:25 UTC] DHCP Server successfully loaded scope file: /etc/dns/config/scopes/VLAN100 - Raspberry Pi (192.168.100.x).scope
> [2020-12-05 06:58:25 UTC] [192.168.123.57:38160] [UDP] System.NullReferenceException: Object reference not set to an instance of an object.
>    at TechnitiumLibrary.ByteTree.ByteTree`2.GetOrAdd(TKey key, Func`2 valueFactory) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.ByteTree\ByteTree.cs:line 172
>    at TechnitiumLibrary.ByteTree.ByteTree`2.GetOrAdd(TKey key, TValue value) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.ByteTree\ByteTree.cs:line 179
>    at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaNameServers, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation) in     Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1503
>    at DnsServerCore.Dns.DnsServer.ProcessRecursiveQueryAsync(DnsDatagram request, IReadOnlyList`1 viaNameServers, IReadOnlyList`1 viaForwarders, Boolean checkForCnameCloaking, Boolean cacheRefreshOperation) in     Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1385
>    at DnsServerCore.Dns.DnsServer.ProcessQueryAsync(DnsDatagram request, IPEndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 930    
> ```

Thanks for the error log. Will fix this issue too.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 fixes this issue.
