### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#214]
```
 at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
[2021-01-02 23:56:57 Local] [113.118.47.143:12636] System.OverflowException: Arithmetic operation resulted in an overflow.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
[2021-01-02 23:56:58 Local] [113.118.47.143:12636] System.OverflowException: Arithmetic operation resulted in an overflow.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
[2021-01-02 23:56:58 Local] [113.118.47.143:12636] System.OverflowException: Arithmetic operation resulted in an overflow.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
[2021-01-02 23:56:59 Local] [113.118.47.143:12636] System.OverflowException: Arithmetic operation resulted in an overflow.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
[2021-01-02 23:56:59 Local] [113.118.47.143:12636] System.OverflowException: Arithmetic operation resulted in an overflow.
   at DnsServerCore.Dns.Zones.DomainTree`1.ConvertKeyToLabel(Byte[] key, Int32 startIndex) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\DomainTree.cs:line 161
   at DnsServerCore.Dns.Zones.ZoneTree`1.ListSubDomains(String domain) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 516
   at DnsServerCore.WebService.ListCachedZones(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 2679
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 652
```

**Comment by ShreyasZare** [comment]
Thanks for the details. Will try to get this fixed.

**Comment by thb007** [comment]
> Thanks for the details. Will try to get this fixed.

ok

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download which fixes this issue.
