### ISSUE TITLE
Conditional forward zone & "this-server"

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#222]
I saw this in the error log:

```
[2021-01-14 00:46:20 UTC] DNS Server recursive resolution failed for QNAME: mbwarez.dk; QTYPE: A; QCLASS: IN; Name Servers: this-server:53;
TechnitiumLibrary.Net.Dns.NameErrorDnsClientException: Domain does not exists: this-server
   at TechnitiumLibrary.Net.Dns.DnsClient.ParseResponseA(DnsDatagram response) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1020
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveIPAsync(String domain, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 986
   at TechnitiumLibrary.Net.Dns.NameServerAddress.RecursiveResolveIPAddressAsync(IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Int32 retries, Int32 timeout) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 538
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaNameServers, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1583
```

The value, `this-server` is funny, because exactly that value is present in my conditional forward zone:

![image](https://user-images.githubusercontent.com/1027111/104631069-02fdb380-569c-11eb-9e8a-d25b0026b30c.png)

.. but it is a value provided by the UI..  :)

![image](https://user-images.githubusercontent.com/1027111/104631081-0729d100-569c-11eb-8576-49504b3efae8.png)

Version info:
`Version 5.6`

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I have already seen this error and a fix will be available in next update. This bug wont affect the usual responses from the DNS server since this is getting triggered by the auto prefetch mechanism. So the response from the DNS server will all be correct for the conditional forwarder zone.

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download which fixes this issue.
