### ISSUE TITLE
Errors in Logs

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#239]
Im seeing this error in the logs

System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at TechnitiumLibrary.IO.StreamExtension.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.IO\StreamExtension.cs:line 37
   at TechnitiumLibrary.Net.Dns.DnsResourceRecord..ctor(Stream s) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsResourceRecord.cs:line 228
   at TechnitiumLibrary.Net.Dns.DnsDatagram.ReadFromUdp(Stream s) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsDatagram.cs:line 188

**Comment by Hemsby** [comment]
And the other error in the logs is 

DnsServerCore.DnsWebServiceException: Invalid username or password: admin
   at DnsServerCore.DnsWebService.LoginAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 927
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 686

Allways then followed by a Success

**Comment by ShreyasZare** [comment]
> 
> 
> Im seeing this error in the logs
> 
> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
> at TechnitiumLibrary.IO.StreamExtension.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.IO\StreamExtension.cs:line 37
> at TechnitiumLibrary.Net.Dns.DnsResourceRecord..ctor(Stream s) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsResourceRecord.cs:line 228
> at TechnitiumLibrary.Net.Dns.DnsDatagram.ReadFromUdp(Stream s) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsDatagram.cs:line 188

Thanks for the feedback. This error is due to the DNS server receiving incomplete or probably corrupt DNS request. The DNS server will respond to such request with Format Error response. These errors are logged just to allow debugging.

**Comment by ShreyasZare** [comment]
> 
> 
> And the other error in the logs is
> 
> DnsServerCore.DnsWebServiceException: Invalid username or password: admin
> at DnsServerCore.DnsWebService.LoginAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 927
> at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 686
> 
> Allways then followed by a Success

When you open the web console on your web browser, the web console tries to login automatically with default password and if the login succeeds then you see the dashboard immediately with a prompt to change password.

So, when you have the password changed, the first attempt made by the web console javascript code fails to login which generates this error log. This is as expected and also gives you the IP address of the person who just tried to visit your DNS web console as a bonus.

**Comment by Hemsby** [comment]
Thanks for clarifying!  Thanks.
