### ISSUE TITLE
stackoverflow exception in logs

### ISSUE THREAD

**Issue by balagurusurendar** [TechnitiumSoftware/DnsServer#288]
[2021-08-09 01:25:57 Local] System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at TechnitiumLibrary.Net.Dns.DnsResourceRecord.get_TtlValue() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsResourceRecord.cs:line 488
   at DnsServerCore.Dns.Zones.CacheZone.RemoveExpiredRecords(Boolean serveStale) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\CacheZone.cs:line 142
   at DnsServerCore.Dns.ZoneManagers.CacheZoneManager.RemoveExpiredRecords() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\ZoneManagers\CacheZoneManager.cs:line 208
   at DnsServerCore.Dns.DnsServer.CacheMaintenanceTimerCallback(Object state) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2357

**Comment by ShreyasZare** [comment]
Thanks for reporting this error. Will get that fixed in next update.

**Comment by ShreyasZare** [comment]
New update v6.4 is now available which fixes this issue.
