### ISSUE TITLE
DNS Server unresponsive at startup

### ISSUE THREAD

**Issue by alexandre-abrioux** [TechnitiumSoftware/DnsServer#299]
Hi,

First of all thanks for a great product, your work is really appreciated!

My issue is that on every Windows startup the DNS server is unresponsive for about a minute. I can access the dashboard but all DNS queries fail, and I get a lot of errors in the logs (see below). It starts working after waiting a bit. Is there something we can do to improve this?

```
[2021-08-29 20:29:22 Local] Logging started.
[2021-08-29 20:29:22 Local] DNS Server config file was loaded: C:\Program Files (x86)\Technitium\DNS Server\config\dns.config
[2021-08-29 20:29:22 Local] DNS Server is loading allowed zone file: C:\Program Files (x86)\Technitium\DNS Server\config\allowed.config
[2021-08-29 20:29:22 Local] DNS Server is loading blocked zone file: C:\Program Files (x86)\Technitium\DNS Server\config\blocked.config
[2021-08-29 20:29:22 Local] DNS Server is reading block list from: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2021-08-29 20:29:22 Local] [127.0.0.1:53] [UDP] DNS Server was bound successfully.
[2021-08-29 20:29:22 Local] [127.0.0.1:53] [TCP] DNS Server was bound successfully.
[2021-08-29 20:29:22 Local] [[::1]:53] [UDP] DNS Server was bound successfully.
[2021-08-29 20:29:22 Local] [[::1]:53] [TCP] DNS Server was bound successfully.
[2021-08-29 20:29:22 Local] [0.0.0.0:5380] HTTP Web Service was started successfully.
[2021-08-29 20:29:22 Local] DNS Server (v6.4.1.0) was started successfully.
[2021-08-29 20:29:22 Local] DNS Server block list file was read (90154 domains) from: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2021-08-29 20:29:22 Local] DNS Server is reading block list from: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
[2021-08-29 20:29:22 Local] DNS Server block list file was read (0 domains) from: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
[2021-08-29 20:29:22 Local] DNS Server block list zone was loaded successfully.
[2021-08-29 20:29:22 Local] DNS Server recursive resolution failed for QNAME: geo.prod.do.dsp.mp.microsoft.com; QTYPE: A; QCLASS: IN; Forwarders: https://cloudflare-dns.com/dns-query;
TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient recursive resolution failed: no response from name servers [j.root-servers.net:53 (192.58.128.30:53), m.root-servers.net:53 (202.12.27.33:53), f.root-servers.net:53 (192.5.5.241:53), c.root-servers.net:53 (192.33.4.12:53), g.root-servers.net:53 (192.112.36.4:53), i.root-servers.net:53 (192.36.148.17:53), b.root-servers.net:53 (199.9.14.201:53), e.root-servers.net:53 (192.203.230.10:53), h.root-servers.net:53 (198.97.190.53:53), a.root-servers.net:53 (198.41.0.4:53), d.root-servers.net:53 (199.7.91.13:53), k.root-servers.net:53 (193.0.14.129:53), l.root-servers.net:53 (199.7.83.42:53)]
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass41_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1767
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, Boolean qnameMinimization, IDnsCache nsResolveCache) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2003
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 627
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 992
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1619
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveIPAsync(String domain, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1034
   at TechnitiumLibrary.Net.Dns.NameServerAddress.RecursiveResolveIPAddressAsync(IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Int32 retries, Int32 timeout) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 566
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2038
[2021-08-29 20:29:22 Local] DNS Server recursive resolution failed for QNAME: login.live.com; QTYPE: A; QCLASS: IN; Forwarders: https://cloudflare-dns.com/dns-query;
TechnitiumLibrary.Net.Dns.DnsClientException: Name server returned error. DNS RCODE: ServerFailure (2)
   at TechnitiumLibrary.Net.Dns.DnsClient.ParseResponseA(DnsDatagram response) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1148
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveIPAsync(String domain, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1034
   at TechnitiumLibrary.Net.Dns.NameServerAddress.RecursiveResolveIPAddressAsync(IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Int32 retries, Int32 timeout) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 566
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2038
[2021-08-29 20:29:22 Local] DNS Server recursive resolution failed for QNAME: [hidden for privacy].net; QTYPE: A; QCLASS: IN; Forwarders: https://cloudflare-dns.com/dns-query;
TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient recursive resolution failed: no response from name servers [b.root-servers.net:53 (199.9.14.201:53), l.root-servers.net:53 (199.7.83.42:53), d.root-servers.net:53 (199.7.91.13:53), k.root-servers.net:53 (193.0.14.129:53), e.root-servers.net:53 (192.203.230.10:53), c.root-servers.net:53 (192.33.4.12:53), g.root-servers.net:53 (192.112.36.4:53), m.root-servers.net:53 (202.12.27.33:53), h.root-servers.net:53 (198.97.190.53:53), f.root-servers.net:53 (192.5.5.241:53), j.root-servers.net:53 (192.58.128.30:53), i.root-servers.net:53 (192.36.148.17:53), a.root-servers.net:53 (198.41.0.4:53)]
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass41_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1767
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, Boolean qnameMinimization, IDnsCache nsResolveCache) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2003
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 627
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 992
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1619
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveIPAsync(String domain, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Int32 retries, Int32 timeout, Int32 maxStackCount) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1034
   at TechnitiumLibrary.Net.Dns.NameServerAddress.RecursiveResolveIPAddressAsync(IDnsCache cache, NetProxy proxy, Boolean preferIPv6, Boolean randomizeName, Boolean qnameMinimization, Int32 retries, Int32 timeout) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 566
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2038
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. These errors are coming since the DNS server has started before your machine is connected to the network. It may happen since the networking service may come up a bit later. Since the network is unreachable during this time, these errors come up and to avoid frequent retries, the DNS server does negative failure caching and creates an entry in the cache with default 60 sec TTL. 

You can set the negative failure caching TTL to lower values so that the DNS server will retry sooner. You can find this option in Setting > Cache with name `Cache Failure TTL` as shown below:

![image](https://user-images.githubusercontent.com/10008172/131297392-ff87bb07-921a-4a67-ac86-292a482379fa.png)

Another observation is that you have a DoH forwarder set with just an URL without specifying an IP address. This will cause the DNS server to perform additional resolution process once before the first call to the DoH server. Better option is to add an IP address for the domain name in the URL so it works faster and also have two entries for both the IP addresses for the cloudflare service as shown below:
```
https://cloudflare-dns.com/dns-query (1.1.1.1)
https://cloudflare-dns.com/dns-query (1.0.0.1)
```

**Comment by alexandre-abrioux** [comment]
> Another observation is that you have a DoH forwarder set with just an URL without specifying an IP address.

Thanks for the tips! I re-selected "Cloudflare (DNS-OVER-HTTPS)" in the quick-select list and it added the IPs automatically :)

> Since the network is unreachable during this time, these errors come up and to avoid frequent retries, the DNS server does negative failure caching and creates an entry in the cache with default 60 sec TTL.

OK, yes that must be it since the errors in the logs literally stop after 60sec.

An idea would be to differentiate the case where the forwarder returns an actual `ServerFailure` response code and we should append the entry to the negative failure cache, with the case where a network failure happens and we shouldn't add the the entry to the negative failure cache.

Do you think we could catch those network exceptions?
What do you think about that idea? Maybe I am overseeing something.

Thanks!

**Comment by ShreyasZare** [comment]
> An idea would be to differentiate the case where the forwarder returns an actual `ServerFailure` response code and we should append the entry to the negative failure cache, with the case where a network failure happens and we shouldn't add the the entry to the negative failure cache.
> 
> Do you think we could catch those network exceptions?
> What do you think about that idea? Maybe I am overseeing something.

In previous versions it was this way and only a response with `ServerFailure` was cached as a failure response. So when there is a network issue, there will be too many errors generated due to constant attempts to resolve the requests. This becomes a big issue when the DNS server is being used with thousands of clients causing too many errors being generated and logged. So, to minimize this, any kind of failure too was cached as a failure record. Its kept default to 60 sec so that its not too small or too large value.

For your use case, since there are not many clients, you can set this value to like 10 sec or even lower and it wont be much noticeable.

**Comment by alexandre-abrioux** [comment]
OK, that works for me :) I'll close the issue. Thanks again for your help!
