### ISSUE TITLE
DNS-over-HTTPS & App Store Not Working

### ISSUE THREAD

**Issue by wan0net** [TechnitiumSoftware/DnsServer#324]
This is with the Docker version.

Both throw an error that state the SSL chain cannot be verified. For example:

[2021-07-19 06:21:24 UTC] DNS Server recursive resolution failed for QNAME: api-global.netflix.com; QTYPE: A; QCLASS: IN; Forwarders: https://cloudflare-dns.com/dns-query (1.1.1.1:443), https://cloudflare-dns.com/dns-query (1.0.0.1:443);
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass40_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1678
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, Boolean qnameMinimization) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1925
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1980

**Comment by wan0net** [comment]
So noting this is on the official Docker image, are you saying I need to go
into the docker image and then update it?

**Comment by ShreyasZare** [comment]
> 
> So noting this is on the official Docker image, are you saying I need to go into the docker image and then update it?

The issue is not with the DNS Server docker image but with the host OS that is missing the CA root certificates. 

On 30th Sept, 2021, Let's Encrypt CA Root cert had expired which will cause issues if the OS does not have the latest certificate updates installed. This is probably the reason why the DNS App Store is failing to load on your setup.
