### ISSUE TITLE
Unable to connect to DoH server that is behind HAProxy

### ISSUE THREAD

**Issue by Taomyn** [TechnitiumSoftware/DnsServer#341]
I have v7.1 of the DNS server working on my Windows laptop well except that I cannot get it to connect to my private DoH server, as a Forwarder. I can set it to any of the DoH protocols and to any of the public DoH servers and it works, but when I try my own server it fails and just gets an error 404. I have tested and used my own DoH within browsers, Firefox, Chrome, Brave, Edge, and via wget on the command-line and it works returning the necessary info in JSON format.

I can only think it's because the DNS server is using the IP and not the FQDN to make the connection because I see no connections arriving at the DoH server itself, only on my firewall. HAProxy proxies all my HTTPS traffic according to hostname, and therefore any HTTPS connections direct to the IP just go to my default web host and nothing else.

```
[2021-11-12 11:06:40 UTC] DNS Server failed to resolve the request with QNAME: www.google.com; QTYPE: A; QCLASS: IN; Forwarders: https://doh.mydomain.com/dns-query (nnn.nnn.nnn.nnn);
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 at TechnitiumLibrary.Net.Dns.ClientConnection.HttpsJsonClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\HttpsJsonClientConnection.cs:line 138
 at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass41_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1828
--- End of stack trace from previous location ---
 at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass41_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1775
--- End of stack trace from previous location ---
 at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, Boolean qnameMinimization, IDnsCache nsResolveCache) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2012
 at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2086
[2021-11-12 11:06:40 UTC] [127.0.0.1:63185] [UDP] QNAME: www.google.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []

```

Is this possibly the problem?

**Comment by ShreyasZare** [comment]
Thanks for the post. From the logs, it does not seem to be an issue with the DNS server itself since its receiving a 404 response for the configured DoH URL.

Since, you are also specifying the IP address to be used by the DNS server for the DoH URL, the DNS server will use that IP address instead of resolving the domain name in the URL. Just make sure that the IP address is correct or just don't specify it and let the DNS server resolve it by itself.

**Comment by Taomyn** [comment]
But I never use the IP address, the forwarder is set with the FQDN in all cases, yet it seems to be using the IP or not setting the hostname correctly in the HTTP requests, which is why the return code is 404 - there is no DoH service running on the default site. The connecting application e.g. a browser, needs to use the FQDN and specify it in the hostname header.

If mydomain.com and doh.mydomain.com both equal 1.2.3.4, then:

https://1.2.3.4/dns-query?name=www.google.com will return 404
https://mydomain.com/dns-query?name=www.google.com will return 404
https://doh.mydomain.com/dnsquery?name=www.google.com will return the expected DNS request result

My DoH service logs all connections and it never shows activity from the DNS server, only from my other devices and manual tests.

**Comment by ShreyasZare** [comment]
Since you control this DoH server, just enable the DoH with HTTP for debugging and use the http URL with the DNS server. Use wireshark or tcpdump on the server running the DNS server and see where the request is heading and the headers in the HTTP request. This way it will be much clear what is going wrong.

**Comment by Taomyn** [comment]
This is the logging from HAProxy.

Using any browser to connect, using the address bar:

```
2021-11-15T08:50:05	haproxy[87792]	nnn.nnn.nnn.nnn:61617 [15/Nov/2021:08:50:05.637] Web_Server_SSL~ DoH/DoH 0/0/0/1/1 404 180 - - ---- 15/15/0/0/0 0/0 "GET https://doh.mydomain.com/favicon.ico HTTP/2.0"	
2021-11-15T08:50:05	haproxy[87792]	nnn.nnn.nnn.nnn:61617 [15/Nov/2021:08:50:05.440] Web_Server_SSL~ DoH/DoH 0/0/1/2/3 200 782 - - ---- 15/15/0/0/0 0/0 "GET https://doh.mydomain.com/dns-query?name=www.google.com HTTP/2.0"	

```
Using the browser DoH option (Brave) to connect:

```
2021-11-15T08:59:08	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:59:08.707] Web_Server_SSL~ DoH/DoH 0/0/0/3/3 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
2021-11-15T08:59:08	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:59:08.258] Web_Server_SSL~ DoH/DoH 0/0/1/44/45 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
2021-11-15T08:58:21	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:58:21.601] Web_Server_SSL~ DoH/DoH 0/0/0/49/49 200 679 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
2021-11-15T08:58:21	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:58:21.478] Web_Server_SSL~ DoH/DoH 0/0/0/2/2 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"

```
Using the DNS server to connnect

```
2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.253] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/0/1/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com&type=28 HTTP/1.1"	
2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.234] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/0/1/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com&type=1 HTTP/1.1"	
2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.218] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/1/0/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com.rotarex.local&type=28 HTTP/1.1"	
2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.032] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/2/0/2 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com.rotarex.local&type=1 HTTP/1.1"

```

DoH/DoH is the HAProxy backend for the DoH server
Apache_Server_Maggie/Apache_Maggie is the HAProxy backend of the main web server and where default HTTP connections are forwarded to which do not specify the full site name

It seems the DNS server does not put the full name in any GET it performs and thus is forwarded to the default web service and not the one for DoH

**Comment by ShreyasZare** [comment]
Thanks for the details. See the response inline:

> This is the logging from HAProxy.
> 
> Using any browser to connect, using the address bar:
> 
> ```
> 2021-11-15T08:50:05	haproxy[87792]	nnn.nnn.nnn.nnn:61617 [15/Nov/2021:08:50:05.637] Web_Server_SSL~ DoH/DoH 0/0/0/1/1 404 180 - - ---- 15/15/0/0/0 0/0 "GET https://doh.mydomain.com/favicon.ico HTTP/2.0"	
> 2021-11-15T08:50:05	haproxy[87792]	nnn.nnn.nnn.nnn:61617 [15/Nov/2021:08:50:05.440] Web_Server_SSL~ DoH/DoH 0/0/1/2/3 200 782 - - ---- 15/15/0/0/0 0/0 "GET https://doh.mydomain.com/dns-query?name=www.google.com HTTP/2.0"	
> ```
> 
> Using the browser DoH option (Brave) to connect:
> 
> ```
> 2021-11-15T08:59:08	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:59:08.707] Web_Server_SSL~ DoH/DoH 0/0/0/3/3 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
> 2021-11-15T08:59:08	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:59:08.258] Web_Server_SSL~ DoH/DoH 0/0/1/44/45 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
> 2021-11-15T08:58:21	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:58:21.601] Web_Server_SSL~ DoH/DoH 0/0/0/49/49 200 679 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"	
> 2021-11-15T08:58:21	haproxy[87792]	nnn.nnn.nnn.nnn:49308 [15/Nov/2021:08:58:21.478] Web_Server_SSL~ DoH/DoH 0/0/0/2/2 200 607 - - ---- 21/21/0/0/0 0/0 "POST https://doh.mydomain.com/dns-query HTTP/2.0"
> ```

In both the cases above the protocol is HTTP/2 and the haproxy is logging it this way.

> Using the DNS server to connnect
> 
> ```
> 2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.253] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/0/1/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com&type=28 HTTP/1.1"	
> 2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.234] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/0/1/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com&type=1 HTTP/1.1"	
> 2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.218] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/1/0/1 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com.rotarex.local&type=28 HTTP/1.1"	
> 2021-11-15T08:49:32	haproxy[87792]	nnn.nnn.nnn.nnn:61610 [15/Nov/2021:08:49:32.032] Web_Server_SSL~ Apache_Server_Maggie/Apache_Maggie 0/0/2/0/2 404 376 - - ---- 14/14/0/0/0 0/0 "GET /dns-query?name=www.google.com.rotarex.local&type=1 HTTP/1.1"
> ```

In the case of DNS server, the protocol is HTTP/1.1 and its logging the first line in the HTTP protocol request.

> DoH/DoH is the HAProxy backend for the DoH server Apache_Server_Maggie/Apache_Maggie is the HAProxy backend of the main web server and where default HTTP connections are forwarded to which do not specify the full site name
> 
> It seems the DNS server does not put the full name in any GET it performs and thus is forwarded to the default web service and not the one for DoH

The domain name part of the given URL comes in the HTTP headers that are after the `GET` line in the logs. In HTTP/1.1 the GET command is passed with only the path and not the full URL except when using a HTTP proxy.

As I suggested in the last response, do try to debug this by using a HTTP url for your DoH server and do a packet capture on the DNS server. A packet capture will show you exactly how the HTTP request is sent unlike logs which shows you only a partial request.

**Comment by Taomyn** [comment]
Ok, well that was not simple as I have zero setup for HTTP on my firewall except to send it all to my honeypot - this is not a business site so I don't care about traffic to port 80.

I've attached a small Wireshark capture which I then had to sanitise so hopefully you'll still see what you need as Wireshark still highlights to the two HTTP traffic portions of the file.

![image](https://user-images.githubusercontent.com/4365929/141776044-9cc6d0c2-469d-4d87-9edd-43c6bd17e508.png)

[DNS_anon.pcapng.txt](https://github.com/TechnitiumSoftware/DnsServer/files/7538368/DNS_anon.pcapng.txt)

**Comment by ShreyasZare** [comment]
Thanks for the pcap file. Just right click on one of the 404 response entry and use **Follow > TCP Stream** option and see the HTTP traffic. You will find the `Host` header with the domain name.

![image](https://user-images.githubusercontent.com/10008172/141777913-da925bf1-32d1-48ac-9d3c-d81a0fbc1c0f.png)

**Comment by Taomyn** [comment]
Right, so that's led me to the issue - it seems that HAProxy (at least on my firewall) checks Host: against the entire host name, so where it's set on my firewall to check for mydomain.com, when the DNS server passes mydomain.com:80 they don't match. Now I know both are correct so the DNS server is not doing anything wrong, but it's strange that everything else I test it with does not add the port to the hostname and so gets detected.

So by changing the HAProxy Host: rule from "host name matches" to "host name starts with" the DNS server now works.

Unfortunately where I am currently working from, work, my browsers are all controlled and so none of them allow me to set the DoH server to see what they set as their Host header, they all revert to the local machine DNS setting. I also see that HTTP/2 has muddied the use of the Host header a bit as well, but I can't find anything specific and I wonder if the browsers are simply using the HTTP/2 definition.

Anyway, thanks for the help, I will now chat with the firewall developers and see what they say about the behaviour of HAProxy i.e. should its check on host name be ignoring the port if specified. I have a dozen or more sites set up in my HAProxy and this is the first time it's ever been a problem.

**Comment by ShreyasZare** [comment]
That's nice find. The `port` part is optional and if missing its considered default port for the scheme. I think it will be better to update the DoH client code to leave out the port number when its default port just to prevent such issues.

**Comment by Taomyn** [comment]
Ok, well if you want me to test let me know and I can revert the check on my HAProxy and see if it still works.

**Comment by ShreyasZare** [comment]
> 
> 
> Ok, well if you want me to test let me know and I can revert the check on my HAProxy and see if it still works.

Sure, I will update the code and upload it on dnsclient.net by weekend. So you can test the DoH URL directly on that web app to check if it works with your setup.

**Comment by ShreyasZare** [comment]
> Ok, well if you want me to test let me know and I can revert the check on my HAProxy and see if it still works.

I have updated code on [dnsclient.net](https://dnsclient.net). If you still have old config then do try once to see if that works with the new code update.

**Comment by Taomyn** [comment]
> I have updated code on [dnsclient.net](https://dnsclient.net). If you still have old config then do try once to see if that works with the new code update.

Normally I wouldn't have an issue and happy to test things out, but as we cannot easily hide a DoH server I don't want it's FQDN to be exposed via anything I do not control. Sorry.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.

**Comment by Taomyn** [comment]
Confirmed working after reverting to "host matches" from workaround "host starts with" - thanks
