### ISSUE TITLE
DNS Server failed to resolve the request with QNAME

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#375]
After updating DNS server to latest I see this error in logs for all local addresses:

```
[2022-03-29 12:21:38 Local] DNS Server failed to resolve the request with QNAME: 10.10.10.10.in-addr.arpa; QTYPE: PTR; QCLASS: IN; Forwarders: cloudflare-dns.com:853 (1.1.1.1), cloudflare-dns.com:853 (1.0.0.1), dns10.quad9.net:853 (9.9.9.10);

TechnitiumLibrary.Net.Dns.DnsClientResponseDnssecValidationException: DNSSEC validation failed as the response was unable to prove non-existence (NX Domain) for owner name: 10.10.10.10.in-addr.arpa
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateResponseAsync(DnsDatagram response, IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2108
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3537
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass64_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3654

--- End of stack trace from previous location ---

   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3074
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3655
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2221
```

As I see I cannot disable DNSSEC for local IPs in DNS server settings.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is an update coming to handle this error correctly. Meanwhile you can disable DNSSEC for such zones by creating conditional forwarder zone. E.g. you can create a 10.in-addr.arpa forwarder zone, with forwarder set to "this-server" and Enable DNSSEC Validation option unchecked to disable DNSSEC validation for that zone.
