### ISSUE TITLE
Apps dont works after latest update

### ISSUE THREAD

**Issue by davidakali** [TechnitiumSoftware/DnsServer#376]
LogQuery app does not work after installing version 8. Uninstalled app and tried reinstall but get the following "Error! No such host is known. (go.technitium.com:443) "
Block list URLs also generating failed to resolve log errors. DNS client feature resolves OK but the application seems not!      

**[2022-03-30 13:57:39 Local] [0.0.0.0:5380] HTTP Web Service was started successfully.
[2022-03-30 13:57:39 Local] DNS Server (v8.0.0.0) was started successfully.
[2022-03-30 13:57:43 Local] DNS Server failed to download block list and will use previously downloaded file (if available): https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
System.Net.Http.HttpRequestException: No such host is known. (s3.amazonaws.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DnsServerCore.Dns.ZoneManagers.BlockListZoneManager.<>c__DisplayClass18_0.<<UpdateBlockListsAsync>g__DownloadListUrlAsync|0>d.MoveNext() in Z:\[Technitium](https://technitium.com/)\Projects\DnsServer\DnsServerCore\Dns\ZoneManagers\BlockListZoneManager.cs:line 331
[2022-03-30 13:57:43 Local] DNS Server failed to download block list and will use previously downloaded file (if available): https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
System.Net.Http.HttpRequestException: No such host is known. (s3.amazonaws.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DnsServerCore.Dns.ZoneManagers.BlockListZoneManager.<>c__DisplayClass18_0.<<UpdateBlockListsAsync>g__DownloadListUrlAsync|0>d.MoveNext() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\ZoneManagers\BlockListZoneManager.cs:line 331
[2022-03-30 13:57:48 Local] Saved zone file for domain: main.local
[2022-03-30 13:57:48 Local] Saved zone file for domain: 0.168.192.in-addr.arpa
[2022-03-30 13:57:52 Local] [192.168.0.51:56001] [admin] User logged in.
[2022-03-30 13:57:52 Local] [192.168.0.51:56006] Check for update was done {updateAvailable: False;}
System.Net.Http.HttpRequestException: No such host is known. (go.technitium.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.DnsWebService.CheckForUpdateAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1138
Technitium | [Blog](https://blog.technitium.com/) | [Donate](https://go.technitium.com/?id=35) | DNS**

**Comment by ShreyasZare** [comment]
Thanks for the post. The error that you are seeing is coming due to the domain names failing to resolve. These calls use the DNS server config that you have on the server. So, the domain names are not resolved by the DNS server itself internally. 

Check if your server's network DNS is "127.0.0.1". Try to query the domain names using the DNS Client tab on the web panel and see if the DNS server is responding to queries.

**Comment by davidakali** [comment]
Thanks  for the response. I was able to resolve the issue by reinstalling to a different directory. On Mar 31, 2022 8:02 AM, Shreyas Zare ***@***.***> wrote:
Thanks for the post. The error that you are seeing is coming due to the domain names failing to resolve. These calls use the DNS server config that you have on the server. So, the domain names are not resolved by the DNS server itself internally.
Check if your server's network DNS is "127.0.0.1". Try to query the domain names using the DNS Client tab on the web panel and see if the DNS server is responding to queries.

**Comment by Xavantex** [comment]
I experience this same issue, I get:
`DNS Server failed to download block list and will use previously downloaded file (if available): https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

System.Net.Http.HttpRequestException: Resource temporarily unavailable (raw.githubusercontent.com:443)`

However seems to be no issue resolving with client using `This Server`

**Comment by ShreyasZare** [comment]
> I experience this same issue, I get: `DNS Server failed to download block list and will use previously downloaded file (if available): https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
> 
> System.Net.Http.HttpRequestException: Resource temporarily unavailable (raw.githubusercontent.com:443)`
> 
> However seems to be no issue resolving with client using `This Server`
> 
> Edit: seems it was an issue with the configured endpoints. had it on local, switched to 0.0.0.0 and running like a well oiled machine. not sure why though. Guessing i am not familiar enogh with DNS Server Local End Points

The HTTP requests use the resolver configured on your system. It may be that the resolver on your system was different than what the DNS server local endpoint was configured to bind on.

**Comment by Xavantex** [comment]
> > I experience this same issue, I get: `DNS Server failed to download block list and will use previously downloaded file (if available): https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
> > System.Net.Http.HttpRequestException: Resource temporarily unavailable (raw.githubusercontent.com:443)`
> > However seems to be no issue resolving with client using `This Server`
> > Edit: seems it was an issue with the configured endpoints. had it on local, switched to 0.0.0.0 and running like a well oiled machine. not sure why though. Guessing i am not familiar enogh with DNS Server Local End Points
> 
> The HTTP requests use the resolver configured on your system. It may be that the resolver on your system was different than what the DNS server local endpoint was configured to bind on.

That was my first thought after reading this issue, I tried changing the system DNS first by netplan to no avail. I also realized afterwords that it could be something else as well, since the router in my network points to the dns-server endpoint. To clarify, the system was configured to use the DHCP served by my router, which point to the DNS-server endpoint for DNS requests.

**Comment by ShreyasZare** [comment]
> > The HTTP requests use the resolver configured on your system. It may be that the resolver on your system was different than what the DNS server local endpoint was configured to bind on.
> 
> That was my first thought after reading this issue, I tried changing the system DNS first by netplan to no avail. I also realized afterwords that it could be something else as well, since the router in my network points to the dns-server endpoint. To clarify, the system was configured to use the DHCP served by my router, which point to the DNS-server endpoint for DNS requests.

It could just be a temporary issue which will get resolved automatically if the config is right.

Seeing this issue, I am updating the HttpClient code used in the DNS server and apps such that the domain in the URL will get resolved internally by the DNS server itself. Thus, it wont matter what DNS server is configured on the system. This change will be available in the next update.
