### ISSUE TITLE
[Bug] System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')

### ISSUE THREAD

**Issue by AlexVerrico** [TechnitiumSoftware/DnsServer#377]
## Environment details: 
Version: 8.0.1
Operating System/Deployment Type: Docker

* * *

## Issue:
When querying for domain `ing.com.au` using various methods (browser, nslookup, etc), the result is a `SERVFAIL`. This behaviour only started after updating to Version 8.0.1.

Please let me know if there is any other information that will help in diagnosing this issue.

* * * 

## Full traceback: 
```
[2022-03-31 01:02:02 Local] [10.0.0.11:33197] [UDP] QNAME: ing.com.au; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2022-03-31 01:02:03 Local] DNS Server failed to resolve the request with QNAME: ing.com.au; QTYPE: A; QCLASS: IN; Forwarders: https://cloudflare-dns.com/dns-query (1.1.1.1), https://cloudflare-dns.com/dns-query (1.0.0.1);
System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.TryParse[TEnum](String value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at TechnitiumLibrary.Net.Dns.ResourceRecords.DnsNSEC3RecordData..ctor(Object jsonResourceRecord) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ResourceRecords\DnsNSEC3RecordData.cs:line 101
   at CallSite.Target(Closure , CallSite , Type , Object )
   at TechnitiumLibrary.Net.Dns.ResourceRecords.DnsResourceRecord..ctor(Object jsonResourceRecord) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ResourceRecords\DnsResourceRecord.cs:line 385
   at CallSite.Target(Closure , CallSite , Type , Object )
   at TechnitiumLibrary.Net.Dns.DnsDatagram.ReadFromJson(Object jsonResponse, Int32 size, DnsDatagramEdns requestEdns) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsDatagram.cs:line 412
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass60_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3264
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3524
   at TechnitiumLibrary.Net.Dns.DnsClient.GetDSForAsync(String ownerName, DnsClass class, IReadOnlyList`1 currentDnsKeyRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, DnsDatagram originalResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2531
   at TechnitiumLibrary.Net.Dns.DnsClient.FindDnsKeyForAsync(String ownerName, DnsClass class, IReadOnlyList`1 currentDnsKeyRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, DnsDatagram originalResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2368
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateResponseAsync(DnsDatagram response, IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1954
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3566
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass64_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3684
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3096
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3685
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2243
[2022-03-31 01:02:03 Local] [10.0.0.11:33197] [UDP] QNAME: ing.com.au; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I would recommend that you do not use the `DNS-over-HTTPS (JSON)` protocol and instead use the `DNS-over-HTTPS` protocol which is a Internet standard. 

The JSON format is non-standard protocol and thus is not well defined. So different implementations return different JSON responses. For example, some send the value as a number and some as the text representation. So there is always a scope for such errors with this protocol.

I will check that the response is coming for this particular domain and try to parse it. This will get updated in next release.

**Comment by AlexVerrico** [comment]
Thanks for the prompt response, changing to `DNS-over-HTTPS` seems to have resolved the issue.
