### ISSUE TITLE
Some DNS names can't be solved with 8.0.2

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#378]
Hi there,

After run version 7.1 for months without an issue, I updated this morning to version 8.0.2 and I noticed that my RSS feeder was not working anymore. I looked at the troubleshooting guide and tried to go the site "feeder.co" and I couldn't. Do I instantly though about DNS and looked at the logs and found that:

```
[2022-04-08 08:17:34 Local] [192.168.XXX.XXX:56951] [UDP] QNAME: play.google.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [172.217.169.46]
[2022-04-08 08:17:34 Local] [192.168.XXX.XXX:49262] [UDP] QNAME: adservice.google.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [0.0.0.0]
[2022-04-08 08:17:34 Local] 
[2022-04-08 08:17:37 Local] [192.168.XXX.XXX:60112] [UDP] QNAME: search24bit.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [104.21.87.24, 172.67.168.171]
[2022-04-08 08:17:38 Local] [192.168.XXX.XXX:59400] [UDP] QNAME: ogs.google.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [www3.l.google.com., 172.217.169.14]
[2022-04-08 08:17:38 Local] [192.168.XXX.XXX:59693] [UDP] QNAME: ssl.gstatic.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [142.250.181.227]
[2022-04-08 08:17:40 Local] [192.168.XXX.XXX:56515] [UDP] QNAME: fe2.update.microsoft.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [fe2.update.msft.com.trafficmanager.net., 52.249.36.203, 52.238.248.0]
[2022-04-08 08:17:42 Local] [192.168.XXX.XXX:60787] [UDP] QNAME: fe3.delivery.mp.microsoft.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [glb.cws.prod.dcat.dsp.trafficmanager.net., 52.242.97.97]
[2022-04-08 08:17:43 Local] 
[2022-04-08 08:17:43 Local] 
[2022-04-08 08:17:47 Local] [192.168.XXX.XXX:60334] [UDP] QNAME: wdcpalt.microsoft.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [wd-prod-cp.trafficmanager.net., wd-prod-cp-us-west-1-fe.westus.cloudapp.azure.com., 13.87.187.111]
[2022-04-08 08:17:50 Local] DNS Server failed to resolve the request with QNAME: feeder.co; QTYPE: A; QCLASS: IN; Forwarders: https://dns.quad9.net/dns-query (9.9.9.9);
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: no response from name servers [https://dns.quad9.net/dns-query (9.9.9.9)].
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass60_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3264
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3538
   at TechnitiumLibrary.Net.Dns.DnsClient.GetDnsKeyForAsync(IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2408
   at TechnitiumLibrary.Net.Dns.DnsClient.FindDnsKeyForAsync(String ownerName, DnsClass class, IReadOnlyList`1 currentDnsKeyRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, DnsDatagram originalResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2378
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateResponseAsync(DnsDatagram response, IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1954
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3566
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass64_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3684
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3096
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3685
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2243
[2022-04-08 08:17:50 Local] [192.168.XXX.XXX:65057] [UDP] QNAME: feeder.co; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
```

This is my forwarders settings (so only one - if it was failing, I would have bigger isssue no?):
![image](https://user-images.githubusercontent.com/28634810/162382631-57bc30c7-e67b-4909-be18-f339ce1acb35.png)

It's kind of weird because most DNS resolutions seemed to work fine (and we can confirm that in this portion of the logs) but the error is strange to me! 😉

Rollback to 7.1 fixed the issue instantly (I snapshot the VMs every time a big change is planned)

**Comment by ShreyasZare** [comment]
Thanks for the post. I have tested this and it seems to be an issue with Quad9 DoH server implementation. This is not observed for other DNS providers like Google or Cloudflare.

You can mitigate this issue by adding either Google or Cloudflare DoH URLs to your forwarders option along with Quad9 OR you can set the **EDNS UDP Payload Size** to 4096 in Settings > General section.

**Comment by EHRETic** [comment]
Hi,

Thanks a lot, I'll try the EDNS payload option and let you know. Google, no thanks and Cloudflare I have issues with my provider because "sometimes" (but you never know when), my Internet box is answering with address 1.1.1.1. It's a known bug with this provider. That is why I'm using Quad9! 😊

Do you have any possible explanation why this site in particular would cause issue (with Quad)?

**Comment by ShreyasZare** [comment]
> Do you have any possible explanation why this site in particular would cause issue (with Quad)? 
> PS: that still doesn't tell me why it works with 7.1! 😉

The new version 8 added support for EDNS and DNSSEC. So, the issue seems to be with Quad9's DoH implementation which is using the EDNS UDP Payload Size in the request for DoH protocol. That option is to be used only with DNS-over-UDP. 

So, when the DNS server is trying to query for DNSKEY of "co" TLD for DNSSEC validation, the response size is larger than the UDP payload size of 1232 and for that the Quad9 server is responding with a truncated response. Since this is an unexpected response over DoH protocol, the DNS Server ignores it and then reports a no response error. Thus failing to validate the original domain name.

I have posted this issue [here](https://lists.dns-oarc.net/pipermail/dns-operations/2022-April/021613.html) so lets hope they confirm and fix it.

**Comment by EHRETic** [comment]
Cool, thanks for the explanation! 😉
(Perfect as usual!)
