### ISSUE TITLE
Interraction with ucrtbase.dll 

### ISSUE THREAD

**Issue by ayo-x** [TechnitiumSoftware/DnsServer#401]
Hello. Running the dns server (auto start) prohibits some apps that use `ucrtbase.dll` from being able to launch, for example WSA and Windows Sandbox. Stopping the server's process via the task manager, `services.msc` or tooltip icon lets both WSA and Windows Sandbox run normally right after. However, after restarting the dns server, it will not resolve queries anymore unless the PC is restarted. Stopping either WSA/Sandbox processes from the task manager, or using their 'Terminate' button from app settings, doesn't fix the dns server not being able to resolve queries.

Event viewer log:
```
Faulting application name: WsaClient.exe, version: 2204.40000.15.0, time stamp: 0x6277155c
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x48cc
Faulting application start time: 0x01d86db00b54814f
Faulting application path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_2204.40000.15.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 28f430fd-ad22-45ed-9969-fad4b71e368a
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2204.40000.15.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```
Dns server log:
```
[2022-05-22 08:13:06 UTC] Logging started.
[2022-05-22 08:13:06 UTC] [[::1]:52921] [admin] All log files were deleted.
[2022-05-22 08:13:08 UTC] DHCP Server successfully unloaded scope: Default
[2022-05-22 08:13:08 UTC] DNS Server (v8.1.1.0) was stopped successfully.
[2022-05-22 08:13:08 UTC] Logging stopped.
[2022-05-22 08:13:08 UTC] Logging started.
[2022-05-22 08:13:09 UTC] DNS Server config file was loaded: C:\Program Files (x86)\Technitium\DNS Server\config\dns.config
[2022-05-22 08:13:09 UTC] DNS Server is loading allowed zone file: C:\Program Files (x86)\Technitium\DNS Server\config\allowed.config
[2022-05-22 08:13:09 UTC] DNS Server is loading blocked zone file: C:\Program Files (x86)\Technitium\DNS Server\config\blocked.config
[2022-05-22 08:13:09 UTC] DNS Server blocked zone file was loaded: C:\Program Files (x86)\Technitium\DNS Server\config\blocked.config
[2022-05-22 08:13:09 UTC] [0.0.0.0:53] [UDP] DNS Server failed to bind.
System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DnsServerCore.Dns.DnsServer.Start() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3075
[2022-05-22 08:13:09 UTC] [0.0.0.0:53] [TCP] DNS Server was bound successfully.
[2022-05-22 08:13:09 UTC] [[::]:53] [UDP] DNS Server was bound successfully.
[2022-05-22 08:13:09 UTC] [[::]:53] [TCP] DNS Server was bound successfully.
[2022-05-22 08:13:09 UTC] DHCP Server successfully loaded scope: Default
[2022-05-22 08:13:09 UTC] DHCP Server successfully loaded scope file: C:\Program Files (x86)\Technitium\DNS Server\config\scopes\Default.scope
[2022-05-22 08:13:09 UTC] [0.0.0.0:5380] HTTP Web Service was started successfully.
[2022-05-22 08:13:09 UTC] DNS Server (v8.1.1.0) was started successfully.
[2022-05-22 08:13:17 UTC] [[::1]:52933] [admin] User logged in.
[2022-05-22 08:13:17 UTC] [[::1]:52937] Check for update was done {updateAvailable: False;}
System.Net.Http.HttpRequestException: No such host is known. (go.technitium.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.DnsWebService.CheckForUpdateAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1138
```

Windows version 22000.675
Dns server version 8.1.1

**Comment by ShreyasZare** [comment]
This is due to conflict with both WSL and the DNS server requiring to use UDP port 53. Check [this issue](https://github.com/TechnitiumSoftware/DnsServer/issues/230) for a solution.

**Comment by ayo-x** [comment]
Thanks, solution worked.
