### ISSUE TITLE
Log Query Issue

### ISSUE THREAD

**Issue by x-tk** [TechnitiumSoftware/DnsServer#402]
Metrics on the analytics dashboard seem correct but I can't query any logs or view any logs in general from the log page.  When I search, it returns blank.  When I go to view the logs, I get the following:

[2022-05-26 00:00:02 UTC] Logging started.
[2022-05-26 00:00:02 UTC] DNS App [Query Logs (Sqlite)]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()

How can I resolve this?

**Comment by ShreyasZare** [comment]
Thanks for the post. The error means that the `querylogs.db` file on disk is corrupt. Most possible reason for this can be power loss but other reasons are also possible. You will need to delete this file or edit the app's config to use a different file name to start over again.

The dashboard data does not come from the Query Log (Sqlite) app so it wont be affected.

**Comment by x-tk** [comment]
Thanks much for the quick response, will delete and report back.

**Comment by x-tk** [comment]
I removed the querylogs.db file as mentioned, got crazy busy and just getting time to circle back... but still have this issue.  What am I missing?  Here's the logs currently:

[2022-08-31 22:32:17 UTC] DNS App [Query Logs (Sqlite)]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at QueryLogsSqlite.App.BulkInsertLogs() in Z:\Technitium\Projects\DnsServer\Apps\QueryLogsSqliteApp\App.cs:line 168

**Comment by ShreyasZare** [comment]
> I removed the querylogs.db file as mentioned, got crazy busy and just getting time to circle back... but still have this issue. What am I missing? Here's the logs currently:
> 
> [2022-08-31 22:32:17 UTC] DNS App [Query Logs (Sqlite)]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'. at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery() at QueryLogsSqlite.App.BulkInsertLogs() in Z:\Technitium\Projects\DnsServer\Apps\QueryLogsSqliteApp\App.cs:line 168

Try uninstalling and reinstalling the app. That will fix it.
