### ISSUE TITLE
TechnitiumLibrary.Net.Dns.DnsClientNxDomainException: Domain does not exists

### ISSUE THREAD

**Issue by amblyo** [TechnitiumSoftware/DnsServer#412]
I get this error in the log.
Can't figure out if their is a general problem or some configuration error on my end.

Any suggestions?

[2022-06-11 14:34:39 UTC] TechnitiumLibrary.Net.Dns.DnsClientNxDomainException: Domain does not exists: network.local
   at TechnitiumLibrary.Net.Dns.DnsClient.ParseResponseDS(DnsDatagram response) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1927
   at DnsServerCore.Dns.Zones.PrimaryZone.GetDSPublishedPrivateKeys(IReadOnlyList`1 privateKeys) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\PrimaryZone.cs:line 1822
   at DnsServerCore.Dns.Zones.PrimaryZone.DnssecTimerCallback(Object state) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\PrimaryZone.cs:line 360

**Comment by ShreyasZare** [comment]
Thanks for the post. It seems you have created "network.local" primary zone and have DNSSEC signed it. So, the server is trying to find out DS record from the parent "local" zone which gives NXDOMAIN error.I would recommend you to unsign your zone since it's a local zone and the error will go way.
