### ISSUE TITLE
Cannot enable stub zone .cyb

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#415]
Hi!
I cannot enable this zone after 31 may 2022 , it's always in expired state.
In log I see 

```
[2022-06-16 15:45:19 Local] TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 317
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass63_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3654
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass63_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3604
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3883
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3907
   at DnsServerCore.Dns.Zones.StubZone.RefreshZoneAsync(IReadOnlyList`1 nameServers) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\StubZone.cs:line 303
```

![image](https://user-images.githubusercontent.com/740757/174074151-aab4af82-42ba-435a-a1d4-6ec01b7c2fb0.png)

All other OpenNIC zones in enabled state.

**Comment by ShreyasZare** [comment]
Thanks for the post. I checked these IP addresses that OpenNIC has on its website. These IP addresses are not authoritative so these can be used only with a Conditional Forwarder Zone and wont work with Stub Zone.

If you wish to use Stub zone then you need to find out the authoritative name server IP addresses for the cyb zone. This can be done by querying any one of those IP addresses you have for cyb NS records and use the IP addresses that are returned as glue in there. I checked with these couple of IP addresses: 79.124.7.8, 161.97.219.84, and it worked.
