### ISSUE TITLE
Sporadic SERVFAIL errors

### ISSUE THREAD

**Issue by GitKepler** [TechnitiumSoftware/DnsServer#424]
DNS Server version: 8.1.3

Hello,

I am currently using the docker setup described [here](https://blog.technitium.com/2021/07/running-root-server-locally-on-your-dns.html) (the updated one, even if the issue was already there with the old one).

Once in a while, I get a SERVFAIL error when I attempt to resolve domain names served by Cloudflare (based on websites I usually browse, so from my end it looks like a cloudflare-specific issue).

As an example (using Windows NSLookup):

```
Serveur par défaut :   UnKnown
Address:  192.168.0.254

> set debug
> www.takethiscourse.net
Serveur :   UnKnown
Address:  192.168.0.254

DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 3, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = AAAA, class = IN
    AUTHORITY RECORDS:
    ->  takethiscourse.net
        ttl = 3600 (1 hour)
        primary name server = adam.ns.cloudflare.com
        responsible mail addr = dns.cloudflare.com
        serial  = 2281208163
        refresh = 10000 (2 hours 46 mins 40 secs)
        retry   = 2400 (40 mins)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)

------------
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 5, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = AAAA, class = IN
    AUTHORITY RECORDS:
    ->  takethiscourse.net
        ttl = 3598 (59 mins 58 secs)
        primary name server = adam.ns.cloudflare.com
        responsible mail addr = dns.cloudflare.com
        serial  = 2281208163
        refresh = 10000 (2 hours 46 mins 40 secs)
        retry   = 2400 (40 mins)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)

------------
*** Le délai de la requête sur UnKnown est dépassé.
```

When I check the logs, I have the following message:

```
[2022-07-01 14:16:05 UTC] DNS Server failed to resolve the request with QNAME: www.takethiscourse.net; QTYPE: A; QCLASS: IN;

TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient recursive resolution failed: no response from name servers [heidi.ns.cloudflare.com (172.64.34.236), adam.ns.cloudflare.com (172.64.33.54)].
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at TechnitiumLibrary.Net.SocketExtension.UdpQueryAsync(Socket socket, ArraySegment`1 request, ArraySegment`1 response, IPEndPoint remoteEP, Int32 timeout, Int32 retries, Boolean expBackoffTimeout, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\SocketExtension.cs:line 141
   at TechnitiumLibrary.Net.Dns.ClientConnection.UdpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\UdpClientConnection.cs:line 77
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass64_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3667
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass64_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3617
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3896
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, UInt16 udpPayloadSize, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Boolean dnssecValidation, Int32 retries, Int32 timeout, Int32 maxStackCount, Boolean cleanupResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 938
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, UInt16 udpPayloadSize, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Boolean dnssecValidation, Int32 retries, Int32 timeout, Int32 maxStackCount, Boolean cleanupResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1537
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2261
```

After a couple seconds, retrying the name resolution returns a different result, albeit still an error:

```
> www.takethiscourse.net
Serveur :   UnKnown
Address:  192.168.0.254

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 6, rcode = SERVFAIL
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 0,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = A, class = IN

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 7, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = AAAA, class = IN
    AUTHORITY RECORDS:
    ->  takethiscourse.net
        ttl = 3540 (59 mins)
        primary name server = adam.ns.cloudflare.com
        responsible mail addr = dns.cloudflare.com
        serial  = 2281208163
        refresh = 10000 (2 hours 46 mins 40 secs)
        retry   = 2400 (40 mins)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 8, rcode = SERVFAIL
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 0,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = A, class = IN

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 9, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = AAAA, class = IN
    AUTHORITY RECORDS:
    ->  takethiscourse.net
        ttl = 3540 (59 mins)
        primary name server = adam.ns.cloudflare.com
        responsible mail addr = dns.cloudflare.com
        serial  = 2281208163
        refresh = 10000 (2 hours 46 mins 40 secs)
        retry   = 2400 (40 mins)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)

------------
*** UnKnown ne parvient pas à trouver www.takethiscourse.net : Server failed
```

After waiting again a couple seconds (no other action from my side), the query now return the expected result:

```
> www.takethiscourse.net
Serveur :   UnKnown
Address:  192.168.0.254

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 10, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 2,  authority records = 0,  additional = 0

    QUESTIONS:
        www.takethiscourse.net, type = A, class = IN
    ANSWERS:
    ->  www.takethiscourse.net
        canonical name = takethiscourse.net
        ttl = 300 (5 mins)
    ->  takethiscourse.net
        internet address = 82.180.174.113
        ttl = 300 (5 mins)

------------
Réponse ne faisant pas autorité :
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
Nom :    takethiscourse.net
Address:  82.180.174.113
Aliases:  www.takethiscourse.net
```

In this example, I tried reaching `www.takethiscourse.net`, but this issue happens somewhat randomly (albeit there is always a cloudflare server in the SOA record).

Do you know if there is a setting which could aleviate this issue (or fix it in the best case) ?

Regards,

**Comment by ShreyasZare** [comment]
Thanks for the post. These are general operational issues that you get when you are running a DNS recursive resolver. The most usual case is the timeout error that you have posted. Its just that your DNS server did not receive a response in time from the authoritative name servers for that domain name.

Your DNS when running as a recursive resolver will have to request to authoritative name servers for the domain names being resolved. There can be cases when you send a lot of queries for different domain names that end up being hosted by the same name server. Some times, these name servers have configured aggressive values for query rate limiting so when you send too many requests, you start seeing timeout errors since those name server are now dropping your requests due to rate limiting.

There can be many other reasons for timeout errors to occur including network issues caused by congestion that would keep dropping your requests for a while. 

I have seen this issue commonly for domains hosted on cloudfront and a few times on cloudflare. The domain eventually resolves with multiple retries and once its resolved, you wont get an issue for that domain again due to Serve Stale feature of the DNS cache. Serve Stale feature will return old data from cache if the name server is taking too long to resolve the domain name. So, if you keep your DNS server running 24x7 then after a few days, you wont get issues with the websites that you usually visit.

**Comment by GitKepler** [comment]
Hello,
Thanks for the quick reply.
Your description of the serve stale feature concurs with what I am currently experiencing (the domain names failing to resolve do not fail again until I restart the server).
It is just a bit annoying, but I guess there is not much I can do from my end (apart from restarting it less often)...
Regards,
