### ISSUE TITLE
[bug] DHCP request with vendor-class-identifier leads to exception

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#476]
I'm running the Debian 10 installer (EOL, yes, don't ask) and during DHCP configuration it does not get an IP. The DHCP server logs this exception below.

I've captured the traffic and extracted samples here.
[bootp-2.zip](https://github.com/TechnitiumSoftware/DnsServer/files/9823927/bootp-2.zip)

```
[2022-10-19 20:07:33 UTC] [0.0.0.0:68] System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DnsServerCore.Dhcp.Scope.GetOptions(DhcpMessage request, IPAddress serverIdentifierAddress, String overrideClientDomainName) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\Scope.cs:line 1046
   at DnsServerCore.Dhcp.DhcpServer.ProcessDhcpMessageAsync(DhcpMessage request, IPEndPoint remoteEP, IPPacketInformation ipPacketInformation) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpServer.cs:line 341
   at DnsServerCore.Dhcp.DhcpServer.ProcessDhcpRequestAsync(DhcpMessage request, IPEndPoint remoteEP, IPPacketInformation ipPacketInformation, Socket udpListener) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpServer.cs:line 299
```

One of the packets has this displayed in Wireshark
```
Dynamic Host Configuration Protocol (Discover)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x04a6002c
    Seconds elapsed: 133
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: Wibrain_51:16:b9 (00:1e:06:51:16:b9)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Discover)
        Length: 1
        DHCP: Discover (1)
    Option: (61) Client identifier
        Length: 7
        Hardware type: Ethernet (0x01)
        Client MAC address: Wibrain_51:16:b9 (00:1e:06:51:16:b9)
    Option: (57) Maximum DHCP Message Size
        Length: 2
        Maximum DHCP Message Size: 576
    Option: (55) Parameter Request List
        Length: 7
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (6) Domain Name Server
        Parameter Request List Item: (12) Host Name
        Parameter Request List Item: (15) Domain Name
        Parameter Request List Item: (28) Broadcast Address
        Parameter Request List Item: (42) Network Time Protocol Servers
    Option: (60) Vendor class identifier
        Length: 3
        Vendor class identifier: d-i
    Option: (255) End
        Option End: 255
    Padding: 0000000000000000000000000000000000000000000000000000000000

```

From the code I can see a relevant setting:
![image](https://user-images.githubusercontent.com/1027111/196794947-aefe8b70-dc3c-445d-8526-177f95c4c8a7.png)

With this DHCP setting, I'm telling Ubiquiti clients to use some specific IP for their controller. This check is for 4 chars and the vendor class identifier for this DHCP request was 3 chars, so an out of bounds occurs. :)
```
substring(vendor-class-identifier,0,4)=="ubnt"
```

**Comment by ShreyasZare** [comment]
Thanks for the bug report. I have found the issue. Will get it fixed in the upcoming release.

Meanwhile, just to make your config work, you can set the identifier to `substring(vendor-class-identifier,0,3)=="ubn"` which should work for your setup.

**Comment by ShreyasZare** [comment]
Version 10 is now released that fixes this issue. Do update and let me know your feedback.
