### ISSUE TITLE
DHCP: Exclusion starting address must be in scope range. (Parameter 'Exclusions')

### ISSUE THREAD

**Issue by melucas** [TechnitiumSoftware/DnsServer#495]
Attempting to add an Exclusion range (192.168.10.1 to 192.168.10.99) for the default DHCP scope.  When saving the scope, a red error message "Error! Exclusion starting address must be in scope range. (Parameter 'Exclusions')" is displayed.

The scope is defined as 192.168.10.100 - 192.168.10.230, 255.255.255.0
The upstream router is 192.168.10.1
Running on a fresh install of Windows 2022 Standard.
The dns server was installed with the Windows installer (v 9.1) and the service is running as a Local System account.

Below is the error from the log file.

Thank you,
Michael

`[2022-11-20 10:37:58 Local] [[::1]:60886] [admin] System.ArgumentOutOfRangeException: Exclusion starting address must be in scope range. (Parameter 'Exclusions')
   at DnsServerCore.Dhcp.Scope.set_Exclusions(IReadOnlyCollection`1 value) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\Scope.cs:line 1661
   at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceDhcpApi.cs:line 611
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 983`

**Comment by Hemsby** [comment]
You are excluding a range 1-99 that is outside of your scope 100-230, so it can't be excluded. If you want this change the scope to start at 1.  Then only reserved or static ip can use the reserved range.  Hope I explained it well enough for you.

Get Outlook for <https://aka.ms/ghei36> Android<https://aka.ms/ghei36>
________________________________
From: Michael Lucas ***@***.***>
Sent: Sunday, November 20, 2022 3:47:05 PM
To: TechnitiumSoftware/DnsServer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TechnitiumSoftware/DnsServer] DHCP: Exclusion starting address must be in scope range. (Parameter 'Exclusions') (Issue #495)


Attempting to add an Exclusion range (192.168.10.1 to 192.168.10.99) for the default DHCP scope. When saving the scope, a red error message "Error! Exclusion starting address must be in scope range. (Parameter 'Exclusions')" is displayed.

The scope is defined as 192.168.10.100 - 192.168.10.230, 255.255.255.0
The upstream router is 192.168.10.1
Running on a fresh install of Windows 2022 Standard.
The dns server was installed with the Windows installer (v 9.1) and the service is running as a Local System account.

Below is the error from the log file.

Thank you,
Michael

[2022-11-20 10:37:58 Local] [[::1]:60886] [admin] System.ArgumentOutOfRangeException: Exclusion starting address must be in scope range. (Parameter 'Exclusions') at DnsServerCore.Dhcp.Scope.set_Exclusions(IReadOnlyCollection1 value) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\Scope.cs:line 1661
at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceDhcpApi.cs:line 611
at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 983`

**Comment by melucas** [comment]
@Hemsby, thank you for the expiation!
