### ISSUE TITLE
Docker: Invalid DNS transport protocol was specified for current operation

### ISSUE THREAD

**Issue by niekvb** [TechnitiumSoftware/DnsServer#497]
First of all, great work on this project, it works like a charm!

I'm trying to deploy the DNS server on Kubernetes but am running into problems when trying to set the env var `DNS_SERVER_FORWARDER_PROTOCOL`.

When I use any of the specified values described in [`docker-compose.yaml`](https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml#L31) it will fail with the following exception:

```plaintext
System.ArgumentException: Invalid DNS transport protocol was specified for current operation: Tls
   at TechnitiumLibrary.Net.Dns.NameServerAddress.ValidateProtocol() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 225
   at TechnitiumLibrary.Net.Dns.NameServerAddress..ctor(String address, DnsTransportProtocol protocol) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 87
   at DnsServerCore.DnsWebService.LoadConfigFile() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 3900
   at DnsServerCore.DnsWebService.Start() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 5269
   at DnsServerApp.Program.Main(String[] args) in Z:\Technitium\Projects\DnsServer\DnsServerApp\Program.cs:line 55

Technitium DNS Server is stopping...
Technitium DNS Server was stopped successfully.
```

**Comment by ShreyasZare** [comment]
Thanks for the post. The forwarder address that you have specified in the `DNS_SERVER_FORWARDERS` var must have port set to 853 to use the Tls protocol. For example, if you have used `1.2.3.4` then make it `1.2.3.4:853` and it will work.

I will update the code to do that automatically in the next release so that this issue gets fixed.

**Comment by niekvb** [comment]
Including the port in the forward address does the trick, thank you!

I'll create a pull request to include my Kubernetes templates in the case you'd like to add them to your repo.

**Comment by ShreyasZare** [comment]
Good to know that it worked. 

I wont be able to maintain the Kubernetes template since I don't have experience running it and have no setup to test it.
