### ISSUE TITLE
ServerFailure

### ISSUE THREAD

**Issue by fogyismstar** [TechnitiumSoftware/DnsServer#510]
After adding the domain name of Conditional Forwarder Zone, I found that returned RCODE = ServerFailure was returned through nslookup query

**Comment by fogyismstar** [comment]
It is known that it is normal to query domain names on the server through nslookup to the dns server at the opposite end, but the prompt times out when querying on the dns client.

**Comment by ShreyasZare** [comment]
Thanks for the post. Do query again and if you see ServerFailure response, just go to the DNS web panel and check the DNS logs for any errors. Share the error log here so that I can help with the issue.

**Comment by fogyismstar** [comment]
[2022-11-30 01:07:22 UTC] DNS Server failed to resolve the request with QNAME: zz.zjedu.gov.cn; QTYPE: A; QCLASS: IN; Forwarders: 10.254.201.196;
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 286
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4041
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3979
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4297
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4319
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass71_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4456
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3908
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4457
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2864

**Comment by fogyismstar** [comment]
[root@dnsserver ~]# nslookup www.qq.com 10.254.201.196
Server:    10.254.201.196
Address 1: 10.254.201.196

Name:      www.qq.com
Address 1: 2402:4e00:1430:1301:0:9227:79cc:76f2
Address 2: 2402:4e00:1430:1301:0:9227:79d3:ffd1
Address 3: 101.91.22.57
Address 4: 101.91.42.232

**Comment by fogyismstar** [comment]
[2022-11-30 01:17:49 UTC] [10.73.12.110:37966] [admin] TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 286
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4041
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3979
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4297
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4319
   at DnsServerCore.DnsWebService.ResolveQueryAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 3642
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1318

**Comment by fogyismstar** [comment]
![image](https://user-images.githubusercontent.com/107558244/204684265-c8764062-5fd1-4bbf-b50c-e78e9135476f.png)

**Comment by ShreyasZare** [comment]
Thanks for the details. Which DNS server are you running at `10.254.201.196`? It seems that the server is not responding correctly for the query over UDP when Randomize Name is enabled. And, also its failing to respond to the next request that is made on TCP port 53.

Try to disable the Randomize Name option in the Settings > Recursion section and try again to see if that works.

If you have configured proxy then make sure to add the IP in bypass list.

**Comment by fogyismstar** [comment]
Randomize Name is disabled, test on dns client or prompt for timeout

**Comment by fogyismstar** [comment]
[2022-11-30 08:58:58 UTC] [10.73.12.110:38034] [admin] TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 286
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4041
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3979
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4297
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4319
   at DnsServerCore.DnsWebService.ResolveQueryAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 3642
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1318

**Comment by fogyismstar** [comment]
[2022-11-30 08:58:39 UTC] [10.73.12.110:38034] [admin] TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request: request timed out.
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 286
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4041
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3979
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4297
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4319
   at DnsServerCore.DnsWebService.ResolveQueryAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 3642
   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1318

**Comment by ShreyasZare** [comment]
For some reason, the UDP request is failing and the DNS client switches to TCP protocol. Then there is timeout issue with the TCP request. There are only 3 reasons why the client switches to TCP: its either the UDP response is failing validation, or the response has truncation bit set, or UDP message size has exceeded the limit.

If you can run tcpdump on your server then it will be able to capture packets that will tell exactly what is wrong. On you linux server you can just run `tcpdump -i any -w filename.pcap` then make the DNS query from the DNS Client and when you see the error then press ctrl+c to stop the tcpdump. Then you can open the pcap file in tools like Wireshark on windows to see the data. You can share that file here or send it via email.

**Comment by fogyismstar** [comment]
tcpdump pcap file see attachment, trouble analysis, thank you!&nbsp;




陌尘
***@***.***







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechnitiumSoftware/DnsServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 晚上6:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechnitiumSoftware/DnsServer] ServerFailure (Issue #510)





 
For some reason, the UDP request is failing and the DNS client switches to TCP protocol. Then there is timeout issue with the TCP request. There are only 3 reasons why the client switches to TCP: its either the UDP response is failing validation, or the response has truncation bit set, or UDP message size has exceeded the limit.
 
If you can run tcpdump on your server then it will be able to capture packets that will tell exactly what is wrong. On you linux server you can just run tcpdump -i any -w filename.pcap then make the DNS query from the DNS Client and when you see the error then press ctrl+c to stop the tcpdump. Then you can open the pcap file in tools like Wireshark on windows to see the data. You can share that file here or send it via email.

**Comment by fogyismstar** [comment]
The pcap file for tcpdump has been sent to support@technitium.com

**Comment by ShreyasZare** [comment]
Thanks for the pcap. It seems you have EDNS Client Subnet enabled on Technitium DNS server. This new feature has some bugs so I would recommend you to disable it for now. There will be a fix available soon. Once the update is available, you can enable the feature again.

**Comment by fogyismstar** [comment]
![image](https://user-images.githubusercontent.com/107558244/204995085-59685e5e-8a41-445c-852c-2aca1c7443ef.png)
Is this the function? It's never been enabled.

**Comment by ShreyasZare** [comment]
> Is this the function? It's never been enabled.

Yes, that the option to enable it. It seems your forwarder running at `10.254.201.196` is returning EDNS Client Subnet in the response (as per the pcap file you sent) which is triggering the bug in Technitium DNS server's EDNS implementation. So, if you can disable it somehow then it should work.

The fix for the bug will be available soon. Most probably on the coming Sunday there will be a minor release that should fix the issue you are facing.

**Comment by ShreyasZare** [comment]
The new update v10.0.1 is now available which should fix this issue. Do update and let me know your feedback.

**Comment by fogyismstar** [comment]
After receiving your message, the first time on the test server upgrade test, the problem has been perfectly resolved. It has been upgraded to version 10.1 on the production server. Thank you very much.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Closing this issue.
