### ISSUE TITLE
Overflow exceptions

### ISSUE THREAD

**Issue by echodreamz** [TechnitiumSoftware/DnsServer#516]
I am seeing this exception quite often in my logs...

`
[2022-12-01 06:47:08 UTC] System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Convert.ThrowByteOverflowException()
   at DnsServerCore.Auth.Permission.WriteTo(BinaryWriter bW) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Auth\Permission.cs:line 311
   at DnsServerCore.Auth.AuthManager.WriteConfigTo(BinaryWriter bW) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Auth\AuthManager.cs:line 368
   at DnsServerCore.Auth.AuthManager.SaveConfigFileInternal() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Auth\AuthManager.cs:line 284
   at DnsServerCore.Auth.AuthManager.SaveTimerCallback(Object state) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Auth\AuthManager.cs:line 101
`

Currently on v10, running on Ubuntu.

**Comment by ShreyasZare** [comment]
Thanks for the bug report. Will get this fixed soon.

**Comment by ShreyasZare** [comment]
The new update v10.0.1 is now available which fixes this issues. Do update and let me know your feedback.
