### ISSUE TITLE
Errors in the log file

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#554]
[TCP] System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at DnsServerCore.Dns.DnsServer.ProcessStreamRequestAsync(Stream stream, MemoryStream writeBuffer, SemaphoreSlim writeSemaphore, IPEndPoint remoteEP, DnsDatagram request, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 649

Im receiving these errors on 1 DNS Server.  I am not noticing these events on other servers running the same OS and DNS Server version.  I am not noticing an errors or impact on the server, just wandered what could cause these to appear in the log.

**Comment by ShreyasZare** [comment]
Thanks for the feedback and details. This is just operational error that can be ignored which is occurring when the TCP transport has been disconnected before the DNS server could send a response to the client. Its coming on one server but not others is due to the sequence of events that are executing. The next update will handle this event and prevent this log from coming.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.0.1 is now available that fixes the issue. Do update and let me know your feedback.
