### ISSUE TITLE
Will not start on homeassistant anymore. 11.0 worked fine

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#565]
System.IO.IOException: The file '/install.sh' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at DnsServerCore.DnsWebService..ctor(String configFolder, Uri updateCheckUri, Uri appStoreUri) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 125
   at DnsServerApp.Program.Main(String[] args) in Z:\Technitium\Projects\DnsServer\DnsServerApp\Program.cs:line 54
Technitium DNS Server is stopping...
Technitium DNS Server was stopped successfully.

**Comment by ShreyasZare** [comment]
Thanks for the post. It seems that you are running the DNS server with `/install.sh` as its command line parameter which is causing this issue since there is already a file with the same name. The command line option is used to specify the config folder path that must be used by the DNS server.

**Comment by ChristoffBo** [comment]
Hi,

Cool so I just need to rename my install.sh say to run.sh

**Comment by ShreyasZare** [comment]
> Hi, Cool so I just need to rename my install.sh say to run.sh

No. You need to check the command that is used to start the DNS server. Remove any parameter that you are passing it.

**Comment by ChristoffBo** [comment]
Hi

#!/bin/sh
mkdir -p /data/technitium
/usr/bin/dotnet /etc/dns/DnsServerApp.dll /data/technitium
exit 1

That is for my storage.

**Comment by ChristoffBo** [comment]
And this is my docker file

ARG BUILD_FROM
FROM ${BUILD_FROM}
ARG BUILD_ARCH
COPY run.sh /
RUN chmod a+x /run.sh
CMD [ "/run.sh" ]
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION
LABEL \
io.hass.name="${BUILD_NAME}" \
io.hass.description="${BUILD_DESCRIPTION}" \
io.hass.arch="${BUILD_ARCH}" \
io.hass.type="addon" \
io.hass.version=${BUILD_VERSION} \
maintainer="christoffbo (https://github.com/ChristoffBo)" \
org.opencontainers.image.title="${BUILD_NAME}" \
org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
org.opencontainers.image.vendor="Home Assistant Add-ons" \
org.opencontainers.image.authors="christoffbo (
https://github.com/ChristoffBo)" \
org.opencontainers.image.licenses="MIT" \
org.opencontainers.image.url="https://github.com/ChristoffBo" \
org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
org.opencontainers.image.documentation="
https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
org.opencontainers.image.created=${BUILD_DATE} \
org.opencontainers.image.revision=${BUILD_REF} \
org.opencontainers.image.version=${BUILD_VERSION}

**Comment by ChristoffBo** [comment]
Rolled back to V11.00 on my home assistant instance works fine again. V11.01 docker image works on my unraid server. Testing quick over tor. Thanks

**Comment by ShreyasZare** [comment]
I think the `CMD` in your Docker file is overwriting the CMD from the [base image](https://github.com/TechnitiumSoftware/DnsServer/blob/master/Dockerfile#L36) causing the "/install.sh" being sent as a command line parameter to the ENTRYPOINT defined in the base image.

**Comment by ChristoffBo** [comment]
Hi,

Ok without Mine it won't have permanent storage. So will stick to V11.0.

Thank you. And awesome software

**Comment by ShreyasZare** [comment]
I am not an expert with docker but, I think if you define an ENTRYPOINT in your docker file instead of CMD then it would work. So try to use `ENTRYPOINT [ "/run.sh" ]` and see if that works.

Second issue is that you need to update your `run.sh` file since the docker image path for the DNS server has changed. So make it:
`/usr/bin/dotnet /opt/technitium/dns/DnsServerApp.dll /data/technitium`

Try these changes and see if that works. Do post here to let me know.

**Comment by ChristoffBo** [comment]
Hi,

now i recieve the below:

The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '/opt/technitium/dns/DnsServerApp.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by ChristoffBo** [comment]
This is what the file looks like now:

!/bin/sh

mkdir -p /data/technitium
/usr/bin/dotnet /opt/technitium/dns/DnsServerApp.dll /data/technitium


exit 1

**Comment by ShreyasZare** [comment]
> The command could not be loaded, possibly because:
> 
>     * You intended to execute a .NET application:
>       The application '/opt/technitium/dns/DnsServerApp.dll' does not exist.
> 
>     * You intended to execute a .NET SDK command:
>       No .NET SDKs were found.
>       Download a .NET SDK:
>       https://aka.ms/dotnet/download
>       Learn about SDK resolution:
>       https://aka.ms/dotnet/sdk-not-found

Check if you have the latest DNS server base image since the new image will have that DLL file in that location.

**Comment by ChristoffBo** [comment]
Hi,

Tested this morning and works again for some odd reason.

You are the MAN. Thank you very much.

**Comment by ShreyasZare** [comment]
You're welcome. Good to know that it worked.
