### ISSUE TITLE
"Access to the path '/etc/dns/blocklists' is denied."

### ISSUE THREAD

**Issue by uberlerd** [TechnitiumSoftware/DnsServer#582]
I've been using the docker available from https://hub.docker.com/r/technitium/dns-server running on Unraid.

This has happened twice now. It occured once on version 11.0.1 and once on version 11.0.2.

The DNS server operates as intended for weeks, and then one day DNS resolution isn't happening. I checked my docker status and it's stopped. Start the container and it stops and present this error:

`System.UnauthorizedAccessException: Access to the path '/etc/dns/blocklists' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at DnsServerCore.DnsWebService..ctor(String configFolder, Uri updateCheckUri, Uri appStoreUri) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 126
   at DnsServerApp.Program.Main(String[] args) in Z:\Technitium\Projects\DnsServer\DnsServerApp\Program.cs:line 54`

**Comment by ShreyasZare** [comment]
Thanks for the post. The docker image has changed its volume path from `/etc/dns/config` to `/etc/dns` which may be the reason for this issue. Do update your container's volume path and it should work.

**Comment by uberlerd** [comment]
I changed the directory from /etc/dns/config to /etc/dns as suggested and that resolved the issue. Thank you.
