### ISSUE TITLE
Domain name synchronization failed 

### ISSUE THREAD

**Issue by fogyismstar** [TechnitiumSoftware/DnsServer#589]
System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.GetConnectionAsync(CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 157
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.SendDnsDatagramAsync(DnsDatagram request, Int32 timeout, Transaction transaction, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 220
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection.QueryAsync(DnsDatagram request, Int32 timeout, Int32 retries, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 305
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4034
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4212
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass67_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3962
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4312
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalNoDnssecResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4334
   at DnsServerCore.Dns.Zones.SecondaryZone.RefreshZoneAsync(IReadOnlyList`1 primaryNameServers, DnsTransportProtocol zoneTransferProtocol, TsigKey key) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\SecondaryZone.cs:line 423

**Comment by fogyismstar** [comment]
Secondary Zone synchronization failed after updating to the latest version. The prompt for deleting and re-adding Secondary Zone is as follows:Error! DnsClient failed to resolve the request: request timed out.

**Comment by ShreyasZare** [comment]
Thanks for the post. The error that you see "Connection timed out" seems to indicate network issue. Check if the primary DNS server is reachable and you are able to connect to TCP port 53 from the secondary server. To test you can try `telnet <primar-dns-ip> 53` and see if the telnet client connects to the port successfully.

Also, if you are manually deleting and re-adding the secondary zone then you do not need to do that. If your primary server's IP changes, you can edit the SOA record in the secondary zone to update it.

**Comment by fogyismstar** [comment]
I re-built the Primary and second DNS server for testing, it seems that there is no problem. I don't think it's a network problem, but it's caused by too much concurrency. Total DNS queries are now 95000+
