### ISSUE TITLE
Time out with QUIC protocol in Windows 11

### ISSUE THREAD

**Issue by dagorret** [TechnitiumSoftware/DnsServer#631]
I have Technitium installed on a Windows 11.
It works perfect with all other protocols.
But with QUIC, regardless of the upstream DNS servers, it never resolves my requests.
I thought it was my network, so I tried AdGuard, and the protocol on the same machine with Windows 11 works fine.

I leave you a screenshot of the log, which I think reveals the situation.
```

[2023-05-21 00:13:27 UTC] DNS Server failed to resolve the request 'google.com. A IN' using forwarders: dns.adguard-dns.com:853 (94.140.14.14), dns.adguard-dns.com:853 (94.140.15.15).

TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request 'google.com. A IN': request timed out.

   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4337

   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4337

   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4387

   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass76_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4501

--- End of stack trace from previous location ---

   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3915

   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4502

   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean conditionalForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2915
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I tested the same forwarders on two separate installations and its working well without any errors. The issue you see could be cause by temporary network issues. Try again and see if its working.

If its still not working then the only way to debug this would be to run Wireshark on your machine and capture the traffic to check what is causing the issue. Do check it with packet capture and if you need help with analyzing it then share the pcap file over email.

**Comment by dagorret** [comment]
It's probably a problem with my network.

Today I did the tests from DNS Client, and it works.

I will try at different times, before putting it definitively.

Thanks for your time.
Excellent work!!!

Have a nice week.

**Comment by ShreyasZare** [comment]
Closing this issue. Open if you still have problem.
