### ISSUE TITLE
DNS App Store error

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#645]
Error! The proxy tunnel request to proxy 'http://127.0.0.1:38235/' failed with status code '500'."

In the settings, I configured Network Proxy socks

**Comment by ShreyasZare** [comment]
Thanks for the post. Please post a screenshot of the error and also any error log you find in the DNS logs.

**Comment by liang-hiwin** [comment]
> Thanks for the post. Please post a screenshot of the error and also any error log you find in the DNS logs.

![HUZ7(1~L8_H~72R(XW}~V~9](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/063486bc-3111-4db2-9a07-a6cb3e6c24e4)

**Comment by liang-hiwin** [comment]
```

[2023-05-28 22:18:05 Local] [112.x.x.x:0] Check for update was done {updateAvailable: False;}
System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://127.0.0.1:40591/' failed with status code '500'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at TechnitiumLibrary.Net.Http.Client.HttpClientNetworkHandler.InternalSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Http\Client\HttpClientNetworkHandler.cs:line 127
   at TechnitiumLibrary.Net.Http.Client.HttpClientNetworkHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Http\Client\HttpClientNetworkHandler.cs:line 260
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.WebServiceApi.GetCheckForUpdateJsonData() in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceApi.cs:line 76
   at DnsServerCore.WebServiceApi.CheckForUpdateAsync(HttpContext context) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebServiceApi.cs:line 100
```

**Comment by liang-hiwin** [comment]
I guarantee that there is no problem with the SOCKS5 Proxy I configured.

**Comment by ShreyasZare** [comment]
> I guarantee that there is no problem with the SOCKS5 Proxy I configured.

Thanks for the details. The http error code 500 is being received from the proxy server. It could be that the URL is not working via the proxy. You can test this by using the proxy with a web browser like Firefox and then check if this URL is working: https://download.technitium.com/dns/apps/apps2.json

**Comment by ShreyasZare** [comment]
> > > I guarantee that there is no problem with the SOCKS5 Proxy I configured.
> > 
> > 
> > Thanks for the details. The http error code 500 is being received from the proxy server. It could be that the URL is not working via the proxy. You can test this by using the proxy with a web browser like Firefox and then check if this URL is working: https://download.technitium.com/dns/apps/apps2.json
> 
> normal

I tested this locally on my setup and its working well without any issues. To debug the issue that you are having, do a packet capture on server that is running the DNS server. If its linux then use `tcpdump -i any -w file.pcap` command and if its windows then use wireshark to capture the traffic. Share the pcap file over email.

**Comment by liang-hiwin** [comment]
> > > > I guarantee that there is no problem with the SOCKS5 Proxy I configured.
> > > 
> > > 
> > > Thanks for the details. The http error code 500 is being received from the proxy server. It could be that the URL is not working via the proxy. You can test this by using the proxy with a web browser like Firefox and then check if this URL is working: https://download.technitium.com/dns/apps/apps2.json
> > 
> > 
> > normal
> 
> I tested this locally on my setup and its working well without any issues. To debug the issue that you are having, do a packet capture on server that is running the DNS server. If its linux then use `tcpdump -i any -w file.pcap` command and if its windows then use wireshark to capture the traffic. Share the pcap file over email.

Hello pcap file I have sent to this email support@technitium.com please check

**Comment by ShreyasZare** [comment]
Thanks for the pcap file. There is a bug causing this issue. Will get it fixed soon in the next update.

**Comment by liang-hiwin** [comment]
Thank you for your dedication

Shreyas Zare ***@***.***> 于2023年6月5日周一 14:23写道：

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which fixes the issue that was discussed. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Version 11.3 is now available which fixes the issue that was discussed. Do update and let me know your feedback.

ok，thanks

**Comment by liang-hiwin** [comment]
> Version 11.3 is now available which fixes the issue that was discussed. Do update and let me know your feedback.

Gladly, the question has been revised. Thanks

**Comment by ShreyasZare** [comment]
Thanks for confirming.
