### ISSUE TITLE
Wrong Forwarder in log file.

### ISSUE THREAD

**Issue by pricerc** [TechnitiumSoftware/DnsServer#672]
I was reading your blog post about DNSSEC, and clicked on a link to IANA but got a DNS lookup failure, which I thought strange, so I went to look at the log and noticed this error:
> DNS Server failed to resolve the request 'www.iana.org. A IN' using forwarders: 1.1.1.1:853, 8.8.8.8:853.
Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest

I recognise this indicates a problem with IANA's own DNSSEC certificate, but the interesting part for me is that I have my forwarders set to AdGuard over TLS, so was surprised to see CloudFlare and Google DNS servers in there, and not the AdGuard servers.
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/22463555/2a2cb04a-6bd9-4854-a79f-323a7d101a50)

I also tried configuring forwarding to AdGuard over UDP, and still got the same message in the log file.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The error is not a DNSSEC related issue but related to TLS. It seems that you have installed Advanced Forwarding DNS app which comes with a default example config to forward all domains to Cloudflare and Google with DoT protocol. Check and uninstall the app if it exists and it will fix the issue. If there is no app installed and you still have this issue then let me know here.

**Comment by pricerc** [comment]
Ahh. So I've removed the App, and I now have the 'correct' DNS servers in my log.

I still can't resolve www.iana.org. Even if I use the built-in DNS client to query 1.1.1.1 directly, it fails when I tick the 'use DNSSEC' option.

The full log entry if I nslookup from my PC (With AdGuard over UDP set on my DNS server):

> [2023-07-01 08:59:46 UTC] DNS Server failed to resolve the request 'www.iana.org. AAAA IN' using forwarders: 94.140.14.15, 94.140.15.16.
Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest
   at Interop.Crypto.RsaVerifyHash(SafeEvpPKeyHandle pkey, RSASignaturePaddingMode paddingMode, IntPtr digestAlgorithm, ReadOnlySpan`1 hash, ReadOnlySpan`1 signature)
   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at TechnitiumLibrary.Net.Dns.Dnssec.DnssecRsaPublicKey.IsSignatureValid(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\Dnssec\DnssecRsaPublicKey.cs:line 100
   at TechnitiumLibrary.Net.Dns.ResourceRecords.DnsRRSIGRecordData.IsSignatureValid(IReadOnlyList`1 records, IReadOnlyList`1 dnsKeyRecords, EDnsExtendedDnsErrorCode& extendedDnsErrorCode) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ResourceRecords\DnsRRSIGRecordData.cs:line 485
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateSignature(DnsDatagram response, IReadOnlyList`1 records, IReadOnlyList`1 dnsKeyRecords, IReadOnlyList`1 unsignedZones, Boolean isAuthoritySection, Boolean isAdditionalSection) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2831
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateSignature(DnsDatagram response, IReadOnlyList`1 dnsKeyRecords, IReadOnlyList`1 unsignedZones) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2622
   at TechnitiumLibrary.Net.Dns.DnsClient.GetDnsKeyForAsync(IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2982
   at TechnitiumLibrary.Net.Dns.DnsClient.FindDnsKeyForAsync(String ownerName, DnsClass class, IReadOnlyList`1 currentDnsKeyRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, DnsDatagram originalResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2873
   at TechnitiumLibrary.Net.Dns.DnsClient.DnssecValidateResponseAsync(DnsDatagram response, IReadOnlyList`1 lastDSRecords, DnsClient dnsClient, IDnsCache cache, UInt16 udpPayloadSize, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 2579
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4427
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass76_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4572
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 3949
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4573
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean conditionalForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2924

**Comment by pricerc** [comment]
I should also add that if I disable DNSSEC in the configuration, the iana.org resolves ok.

**Comment by ShreyasZare** [comment]
> Ahh. So I've removed the App, and I now have the 'correct' DNS servers in my log.
> 
> I still can't resolve [www.iana.org](http://www.iana.org). Even if I use the built-in DNS client to query 1.1.1.1 directly, it fails when I tick the 'use DNSSEC' option.
> 
> The full log entry if I nslookup from my PC (With AdGuard over UDP set on my DNS server):

Thanks for the full error log. Its now clear that the error is occurring when DNSSEC signature validation is being done. 

But, disabling DNSSEC validation when you see such issues is not recommended. If you were using DNS-over-UDP with those forwarders then switch to DNS-over-TLS and test again with DNSSEC validation enabled. With UDP, its possible that the response is being tampered on your network which may cause such errors and disabling validation is just giving up on security.

I have just [checked using dnsclient.net](https://dnsclient.net/#94.140.14.15/www.iana.org/A/TLS/true) for the same forwarders with DoT and DNSSEC validation and it seems to be working well.

**Comment by pricerc** [comment]
> But, disabling DNSSEC validation when you see such issues is not recommended.

I only did it to test :)

I still get an error from my server:
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/22463555/843f017b-b0d9-40ba-b373-f583e62e7734)

**Comment by ShreyasZare** [comment]
> I still get an error from my server: ![image](https://user-images.githubusercontent.com/22463555/250269551-843f017b-b0d9-40ba-b373-f583e62e7734.png)

Thanks for the feedback. It seems to be installation specific issue. Which OS are you running the DNS server on? Can you validate any other signed domain name like `example.com` without the same error?

**Comment by ShreyasZare** [comment]
If you are using [CentOS or RHEL](https://access.redhat.com/documentation/en-us/net/6.0/html/release_notes_for_.net_6.0_rpm_packages/known-issues_release-notes-for-dotnet-rpms) then it seems to be the case of OpenSSL disabling RSA+SHA1 signature generation and validation. This is affecting `www.iana.org` being resolved since it has CNAME to `ianawww.vip.icann.org` and `icann.org` uses RSA+SHA1 signing algorithm which will result with the error you see.

You can see the same issue being discussed [here](https://github.com/dotnet/runtime/issues/65874). The workaround is the set environment variable:
`OPENSSL_ENABLE_SHA1_SIGNATURES=1`

**Comment by pricerc** [comment]
Ahh, I'm running AlmaLinux on a Pi 4, so it will be affected.

where do I put that environment variable?

**Comment by pricerc** [comment]
never mind, found it - in the systemd/.../dns.service file:

'
[Unit]
Description=Technitium DNS Server

[Service]
WorkingDirectory=/opt/technitium/dns
Environment="OPENSSL_ENABLE_SHA1_SIGNATURES=1"
ExecStart=/usr/bin/dotnet /opt/technitium/dns/DnsServerApp.dll /etc/dns
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dns-server

[Install]
WantedBy=multi-user.target
`

**Comment by ShreyasZare** [comment]
Good to know that you found how to set the environment variable for the systemd service and that it fixes the issue.

**Comment by ShreyasZare** [comment]
Closing this issue since its fixed.
