### ISSUE TITLE
 [BUG] ServerFailure multiple domains with 11.5 release

### ISSUE THREAD

**Issue by brokoler** [TechnitiumSoftware/DnsServer#764]
Hello,

I just happily updated to 11.5 and discovered issues on my end devices.
For example my iPhone told me it's offline now, I did not have any issues with 11.4.1

I checked my server logs and see following:
![grafik](https://github.com/TechnitiumSoftware/DnsServer/assets/57031979/ca978471-9412-4982-99b5-34b0541701e2)
![grafik](https://github.com/TechnitiumSoftware/DnsServer/assets/57031979/75ee378c-3b2e-4c19-9904-750b4555b439)

Many more domains are affected, the screenshots above show the issue for my iPhone telling me it's offline.

Could this be fixed rather soon?
I will downgrade for now.

Kind regards

**Comment by brokoler** [comment]
Confirming the issue is gone after downgrading to 11.4.1.
I will stay with 11.4.1 for now.

**Comment by scott-feier** [comment]
Similar for me. I had DNS over TLS setup to Quad9 Secure, and was getting a ton of errors. Changed to DNS over UDP and issues disappeared. Here's a typical log entry:

```
[2023-10-29 15:59:36 Local] DNS Server failed to resolve the request 'd3p8zr0ffa9t17.cloudfront.net. A IN' using forwarders: dns.quad9.net:853 (9.9.9.9), dns.quad9.net:853 (149.112.112.112).

System.ArgumentException: Name server protocol does not match. (Parameter 'server')
   at TechnitiumLibrary.Net.Dns.ClientConnection.TcpClientConnection..ctor(NameServerAddress server, NetProxy proxy) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TcpClientConnection.cs:line 60
   at TechnitiumLibrary.Net.Dns.ClientConnection.TlsClientConnection..ctor(NameServerAddress server, NetProxy proxy) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\TlsClientConnection.cs:line 44
   at TechnitiumLibrary.Net.Dns.ClientConnection.DnsClientConnection.<>c__DisplayClass17_0.<GetConnection>b__3(NetProxy netProxyKey) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\DnsClientConnection.cs:line 232
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at TechnitiumLibrary.Net.Dns.ClientConnection.DnsClientConnection.GetConnection(NameServerAddress server, NetProxy proxy) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\ClientConnection\DnsClientConnection.cs:line 277
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass73_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4140
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass73_0.<<InternalResolveAsync>g__DoResolveAsync|1>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4072
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4423
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalResolveAsync(DnsDatagram request, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4423
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalDnssecResolveAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4479
   at TechnitiumLibrary.Net.Dns.DnsClient.<>c__DisplayClass77_0.<<InternalCachedResolveQueryAsync>b__0>d.MoveNext() in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4644
--- End of stack trace from previous location ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveQueryAsync(DnsQuestionRecord question, Func`2 resolveAsync) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4001
   at TechnitiumLibrary.Net.Dns.DnsClient.InternalCachedResolveQueryAsync(DnsQuestionRecord question, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 4645
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean conditionalForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3066

```

**Comment by r00m55** [comment]
I am also getting this same error. How do I downgrade to the previous v11.4.1?

**Comment by brian-wee** [comment]
> I am also getting this same error. How do I downgrade to the previous v11.4.1?

https://download.technitium.com/dns/archive/11.4.1/

@r00m55

**Comment by brian-wee** [comment]
Having the same issue on DNS over TLS, changing to DNS over UDP solved it for me.

**Comment by ShreyasZare** [comment]
Thanks for reporting this issue. It an issue only with DNS-over-TLS so switching to another protocol will help mitigate the issue meanwhile. An update for the bug fix will be made available very soon.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.1 is now available that fixes this issue. Do update and confirm.

**Comment by djarbz** [comment]
11.5.1 does not resolve it for me, using the built in DNS Client I get the following when attempting to resolve `reddit.com` using `This Server` and `DNS-over-UDP`.

```json
{
  "Metadata": {
    "NameServer": "<REDACTED> ([::1])",
    "Protocol": "Udp",
    "DatagramSize": "149 bytes",
    "RoundTripTime": "3.7 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "ServerFailure",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "100 bytes",
        "Data": {
          "InfoCode": "Other",
          "ExtraText": "Resolver exception for reddit.com. A IN: Name server protocol does not match. (Parameter 'server')"
        }
      },
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "2 bytes",
        "Data": {
          "InfoCode": "CachedError",
          "ExtraText": null
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [
    {
      "InfoCode": "NetworkError",
      "ExtraText": "<REDACTED> ([::1]) returned RCODE=ServerFailure for reddit.com. A IN"
    }
  ],
  "Identifier": 62723,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "ServerFailure",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "reddit.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "1232",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "110 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "100 bytes",
            "Data": {
              "InfoCode": "Other",
              "ExtraText": "Resolver exception for reddit.com. A IN: Name server protocol does not match. (Parameter 'server')"
            }
          },
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "2 bytes",
            "Data": {
              "InfoCode": "CachedError",
              "ExtraText": null
            }
          }
        ]
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```
