### ISSUE TITLE
Seeing, System.ArgumentNullException: Value cannot be null in logs

### ISSUE THREAD

**Issue by josemanimala** [TechnitiumSoftware/DnsServer#838]
I recently setup a new server and am seeing the error below in the logs.

```
[2024-01-28 14:13:23 UTC] System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at DnsServerCore.Dns.Zones.PrimaryZone.DnssecTimerCallback(Object state) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\PrimaryZone.cs:line 472
[2024-01-28 14:17:18 UTC] System.ArgumentNullException: Value cannot be null.
```

Server is running: 11.5.3. 
Ubuntu 22.04 LTS.

**Comment by ShreyasZare** [comment]
Thanks for reporting this. Will get that fixed in the next update.

**Comment by josemanimala** [comment]
Thank you @ShreyasZare

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that fixes this issue. Do update and let me know your feedback.
