### ISSUE TITLE
DNS Service keeps crashing, require restart

### ISSUE THREAD

**Issue by GChester** [TechnitiumSoftware/DnsServer#9]
About 1 or 2 times a day the DNS Service will stop and we need to restart the service.

Any ideas how to track down the problem and solve?

**Comment by GChester** [comment]
Now we are crashing about every 10 mins.  Not usable.

**Comment by ShreyasZare** [comment]
Hi @GChester ,

Thanks for the feedback. It would be really helpful if you can share the DNS Server log files. You can find it at [installation folder]/config/logs/.

Also, check Windows Event Viewer and send the crash log for the DNS Service. 

Both the logs will help in finding the reason for the crash. Meanwhile, you can configure the service to restart automatically when it crashes from the Windows Services console window. You will find the option inside the service properties.

Thanks,
Shreyas Zare

**Comment by GChester** [comment]
[2018-09-04 07:00:36 UTC] [10.24.9.99:52268] TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient failed to resolve the request: no response from name servers. ---> TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient failed to resolve the request: no response from name servers. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at TechnitiumLibrary.Net.Dns.DnsClient.Resolve(DnsDatagram request)
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.Resolve(DnsDatagram request)
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveViaNameServers(DnsQuestionRecord question, NameServerAddress[] nameServers, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, DnsClientProtocol protocol, Int32 retries, Int32 maxStackCount)
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveViaNameServers(DnsQuestionRecord question, NameServerAddress[] nameServers, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, DnsClientProtocol protocol, Int32 retries, Int32 maxStackCount)
   at DnsServerCore.DnsServer.ProcessRecursiveQuery(DnsDatagram request)
   at DnsServerCore.DnsServer.ProcessQuery(DnsDatagram request, EndPoint remoteEP)

**Comment by ShreyasZare** [comment]
This error log snippet just says that DNS server didn't receive any response from name server, probably due to network errors. This is not related to crash.

**Comment by natiki** [comment]
@ShreyasZare I see 2.0 is still a BETA version per the website. Is this correct?

**Comment by ShreyasZare** [comment]
Hi @natiki,

Yes, that is correct since its still getting stability fixes. Once its proved to be stable then the beta tag will be removed.

Regards,
Shreyas Zare
