### ISSUE TITLE
Server Failure

### ISSUE THREAD

**Issue by decoderid** [TechnitiumSoftware/DnsServer#950]
How to solve Server Failure problem?

installed under docker container

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/75539501/7eddc00c-75b8-477f-98d1-cf227b4812ca)

**Comment by ShreyasZare** [comment]
Thanks for the post. Server Failure responses are generic and they just mean that the domain name could not be resolved in given time. To know what went wrong, you need to check the DNS logs from the panel. If you need help understanding the error logs, then post them here.

**Comment by decoderid** [comment]
So many Server Failure:

![{A8A54179-D28B-4CFA-BF58-6C7B7F4CC353}](https://github.com/user-attachments/assets/1a2aafb1-4c73-414c-b235-20e80f2f8213)

Here is log file.
```txt
[2024-09-11 00:00:02 UTC] Logging started.
[2024-09-11 00:00:02 UTC] DNS Server failed to resolve the request 'rdate.darkorb.net. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'rdate.darkorb.net. A IN' with RCODE=ServerFailure from: 1.1.1.2
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:02 UTC] DNS Server failed to resolve the request 'speedtest-bali.smartconnect.id. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'speedtest-bali.smartconnect.id. A IN' with RCODE=ServerFailure from: 1.1.1.1
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:08 UTC] DNS Server failed to resolve the request 'rdate.darkorb.net. AAAA IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'rdate.darkorb.net. AAAA IN' with RCODE=ServerFailure from: 1.1.1.2
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:08 UTC] DNS Server failed to resolve the request 'speedtest.jaosing.com. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'speedtest.jaosing.com. A IN' with RCODE=ServerFailure from: 1.1.1.2
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:12 UTC] DNS Server failed to resolve the request 'speedtest-bali.smartconnect.id. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'speedtest-bali.smartconnect.id. A IN' with RCODE=ServerFailure from: 1.1.1.2
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:14 UTC] DNS Server failed to resolve the request 'rdate.darkorb.net. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'rdate.darkorb.net. A IN' with RCODE=ServerFailure from: 1.1.1.1
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210
[2024-09-11 00:00:18 UTC] DNS Server failed to resolve the request 'speedtest.jaosing.com. A IN' using forwarders: 1.1.1.1, 1.1.1.2.
DnsServerCore.Dns.DnsServerException: DNS Server received a response for 'speedtest.jaosing.com. A IN' with RCODE=ServerFailure from: 1.1.1.2
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, NetworkAddress eDnsClientSubnet, Boolean advancedForwardingClientSubnet, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, Boolean skipDnsAppAuthoritativeRequestHandlers, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 3210


####___TRUNCATED___####
```

**Comment by ShreyasZare** [comment]
Thanks for the error logs.

> DNS Server received a response for 'rdate.darkorb.net. A IN' with RCODE=ServerFailure from: 1.1.1.2

The error logs say that your upstream servers are returning `ServerFailure` response. I tried to test those domain names using the DNS Client tool on the admin panel and all of those domain names have issues with their config which is why they cannot be resolved. Which is why Cloudflare is returning `ServerFailure` response since they are unable to resolve those domain names.

There is nothing you can do here and you just need to ignore these cases.
