### ISSUE TITLE
After updating the version,There are many error logs appearing, and the log content is:

### ISSUE THREAD

**Issue by MidnightShake** [TechnitiumSoftware/DnsServer#982]
the log content is:
[2024-08-01 03:06:20 UTC] [0.0.0.0:0] [UDP] System.MissingMethodException: Method not found: 'TechnitiumLibrary.Net.Dns.DnsDatagram TechnitiumLibrary.Net.Dns.IDnsCache.Query(TechnitiumLibrary.Net.Dns.DnsDatagram, Boolean, Boolean)'.
   at DnsFallbackApp.App.ProcessRequestAsync(DnsDatagram request, IPEndPoint remoteEP, DnsTransportProtocol protocol, Boolean isRecursionAllowed)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DnsFallbackApp.App.ProcessRequestAsync(DnsDatagram request, IPEndPoint remoteEP, DnsTransportProtocol protocol, Boolean isRecursionAllowed)
   at DnsServerCore.Dns.DnsServer.AuthoritativeQueryAsync(DnsDatagram request, IPEndPoint remoteEP, DnsTransportProtocol protocol, Boolean isRecursionAllowed, Boolean skipDnsAppAuthoritativeRequestHandlers) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2124

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is expected and the issue will go away when the DNS app gets updated automatically. Just check once on the Apps section on the panel to see if all the apps have been updated. If any of the apps show that update is available, then click on the Store Update button to manually update them.

**Comment by MidnightShake** [comment]
Thank you. Based on this reminder, I have checked the app and found that the issue occurred on the custom app. It has been resolved
